# Alacritty Terminal Configuration

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 5, y = 3 }
dynamic_padding = false
decorations = "Full"
opacity = 1.0
blur = true
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
decorations_theme_variant = "Dark"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 12.0
offset = { x = 0, y = 0}

[font.normal]
family = "Iosevka Comfy"
style = "Light"

[font.bold]
family = "Iosevka Comfy"
style = "Regular"

[font.italic]
family = "Iosevka Comfy"
style = "Light Oblique"

[font.bold_italic]
family = "Iosevka"
style = "Light Italic"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#1a1a1a"
foreground = "#e5e9f0"

[colors.search]
matches = { foreground = "#1a1a1a", background = "#ff6c6b" }
focused_match = { foreground = "#1a1a1a", background = "#e0af68" }

[colors.hints]
start = { foreground = "#1a1a1a", background = "#9ece6a" }
end = { foreground = "#1a1a1a", background = "#7aa2f7" }

[colors.normal]
black = "#1a1a1a"
red = "#ff6c6b"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#c678dd"
cyan = "#46d9ff"
white = "#e5e9f0"

[colors.bright]
black = "#414868"
red = "#ff7a93"
green = "#b9f27c"
yellow = "#ffca80"
blue = "#51afef"
magenta = "#c99efc"
cyan = "#86e1fc"
white = "#eceff4"

[colors.dim]
black = "#121212"
red = "#d15c5b"
green = "#7aa85c"
yellow = "#c99a56"
blue = "#5c7eae"
magenta = "#a16aa3"
cyan = "#3ba2c9"
white = "#b4bcc6"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = false
thickness = 0.2

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = false
bindings = [
    { mouse = "Right", mods = "Control", action = "Paste" },
    { mouse = "Middle", mods = "None", action = "Paste" },
    { mouse = "Left", mods = "Shift", action = "ExpandSelection" }
]

[hints]
alphabet = "asdfghjklqwertyuiopzxcvbnm"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "O", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]
bindings = [
    # Clipboard
    { key = "Y", mods = "Control", action = "Paste" },
    { key = "V", mods = "Control|Shift", action = "Paste" },
    { key = "W", mods = "Control", action = "Copy" },
    { key = "C", mods = "Control|Shift", action = "Copy" },
    # Font Size
    { key = "Equals", mods = "Control|Shift", action = "IncreaseFontSize" },
    { key = "Minus", mods = "Control|Shift", action = "DecreaseFontSize" },
    { key = "Key0", mods = "Control|Shift", action = "ResetFontSize" },
    # Scrolling
    { key = "PageUp", mods = "None", action = "ScrollPageUp" },
    { key = "PageDown", mods = "None", action = "ScrollPageDown" },
    { key = "P", mods = "Shift", action = "ScrollHalfPageUp" },
    { key = "N", mods = "Shift", action = "ScrollHalfPageDown" },
    { key = "P", mods = "Control", action = "ScrollLineUp" },
    { key = "N", mods = "Control", action = "ScrollLineDown" },
    { key = "P", mods = "Control|Shift", action = "ScrollToTop" },
    { key = "N", mods = "Control|Shift", action = "ScrollToBottom" },
    # History and Clearing
    { key = "L", mods = "Control|Shift", action = "ClearLogNotice" },
    { key = "L", mods = "Control", action = "ReceiveChar" },
    # Window Management
    { key = "T", mods = "Control|Alt", action = "SpawnNewInstance" },
    { key = "F11", mods = "None", action = "ToggleFullscreen" },
    { key = "Z", mods = "Control|Shift", action = "ToggleMaximized" },
    # Search
    { key = "R", mods = "Control", action = "SearchBackward" },
    { key = "S", mods = "Control", action = "SearchForward" },
    { key = "D", mods = "Control|Shift", action = "SearchClear" },
    { key = "O", mods = "Control|Shift", action = "SearchNext" },
    { key = "I", mods = "Control|Shift", action = "SearchPrevious" },
    { key = "H", mods = "Control|Shift", action = "SearchHistoryPrevious" },
    { key = "L", mods = "Control|Shift", action = "SearchHistoryNext" },
    # URL Opening
    { key = "O", mods = "Alt", action = "Open" },
]

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false
prefer_egl = true