# Alacritty Terminal Configuration

# Colors settings
[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4c566a"
blue = "#51afef"
cyan = "#46D9FF"
green = "#99bb66"
magenta = "#c678dd"
red = "#ff6655"
white = "#eceff4"
yellow = "#ECBE7B"

[colors.normal]
black = "#1a1a1a"
blue = "#51afef"
cyan = "#46D9FF"
green = "#98be65"
magenta = "#c678dd"
red = "#ff6c6b"
white = "#e5e9f0"
yellow = "#ECBE7B"

[colors.primary]
background = "#1a1a1a"
foreground = "#d8dee9"

# Environment settings
[env]
TERM = "xterm-256color"

# Font settings
[font]
size = 12.0

[font.bold]
family = "Iosevka Comfy"
style = "Regular"

[font.bold_italic]
family = "Iosevka"
style = "Light Italic"

[font.italic]
family = "Iosevka Comfy"
style = "Light Oblique"

[font.normal]
family = "Iosevka Comfy"
style = "Light"

# Keyboard bindings
[[keyboard.bindings]]
key = "W"
mods = "Alt"
action = "Copy"

[[keyboard.bindings]]
key = "Y"
mods = "Alt"
action = "Paste"

[[keyboard.bindings]]
key = "Right"
mods = "Control"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Left"
mods = "Control"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "PageUp"
mode = "~Alt"
mods = "None"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mode = "~Alt"
mods = "None"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mode = "~Alt"
mods = "Shift"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mode = "~Alt"
mods = "Shift"
action = "ScrollToBottom"

# Scrolling configuration
[scrolling]
history = 100000
multiplier = 3

# Window settings
[window]
decorations = "full"
dynamic_padding = true
startup_mode = "Windowed"
padding = { x = 5, y = 3 }

[window.dimensions]
columns = 100
lines = 25
