# Alacritty Terminal Configuration

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
print_events = false

[window]
dimensions = { columns = 0, lines = 0 }
decorations = "full"
dynamic_padding = false
startup_mode = "Windowed"
padding = { x = 5, y = 3 }

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4c566a"
blue = "#51afef"
cyan = "#46D9FF"
green = "#99bb66"
magenta = "#c678dd"
red = "#ff6655"
white = "#eceff4"
yellow = "#ECBE7B"

[colors.normal]
black = "#1a1a1a"
blue = "#51afef"
cyan = "#46D9FF"
green = "#98be65"
magenta = "#c678dd"
red = "#ff6c6b"
white = "#e5e9f0"
yellow = "#ECBE7B"

[colors.primary]
background = "#1a1a1a"
foreground = "#d8dee9"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Iosevka Comfy"
style = "Regular"

[font.bold_italic]
family = "Iosevka"
style = "Light Italic"

[font.italic]
family = "Iosevka Comfy"
style = "Light Oblique"

[font.normal]
family = "Iosevka Comfy"
style = "Light"

[cursor]
style = "Block"
unfocused_hollow = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = true

[scrolling]
history = 100000
multiplier = 3

[mouse]
hide_when_typing = false

[[keyboard.bindings]]
key = "A"
mods = "Control"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "E"
mods = "Control"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "F"
mods = "Control"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "B"
mods = "Control"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "V"
mods = "Control"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "V"
mods = "Alt"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "L"
mods = "Control"
action = "ClearLogNotice"

[[keyboard.bindings]]
key = "R"
mods = "Control"
action = "SearchBackward"

[[keyboard.bindings]]
key = "S"
mods = "Control"
action = "SearchForward"

[[keyboard.bindings]]
key = "K"
mods = "Control"
action = "ClearHistory"

[[keyboard.bindings]]
key = "Y"
mods = "Control"
action = "Paste"

[[keyboard.bindings]]
key = "W"
mods = "Control"
action = "Copy"

[[keyboard.bindings]]
key = "X"
mods = "Control|Alt"
action = "Quit"

[[keyboard.bindings]]
key = "T"
mods = "Control|Alt"
action = "SpawnNewInstance"

[[keyboard.bindings]]
key = "Equals"
mods = "Control|Shift"
action = "IncreaseFontSize"

[[keyboard.bindings]]
key = "Minus"
mods = "Control|Shift"
action = "DecreaseFontSize"

[[keyboard.bindings]]
key = "Key0"
mods = "Control|Shift"
action = "ResetFontSize"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "PageUp"
mods = "None"
action = "ScrollPageUp"

[[keyboard.bindings]]
key = "PageDown"
mods = "None"
action = "ScrollPageDown"

[[keyboard.bindings]]
key = "Home"
mods = "Shift"
action = "ScrollToTop"

[[keyboard.bindings]]
key = "End"
mods = "Shift"
action = "ScrollToBottom"

[[keyboard.bindings]]
key = "Tab"
mods = "Shift"
chars = '\x1b[Z'

[[keyboard.bindings]]
key = "Backspace"
mods = "Alt"
chars = '\x1b\x7f'
