;;; bv-themes-adapters.el --- Package face adapters for BV themes -*- lexical-binding: t -*-

;; Copyright (C) 2026 Ayan Das
;; Author: Ayan Das <bvits@riseup.net>

;;; Commentary:

;; Adapters map concrete Emacs and package faces to semantic roles.  Package
;; faces stay explicit so workflow-specific meaning is not flattened into raw
;; palette use.

;;; Code:

(require 'cl-lib)
(require 'subr-x)

(defface bv-face-default '((t :inherit default))
  "BV default semantic face."
  :group 'bv-themes)

(defface bv-face-muted '((t :inherit shadow))
  "BV muted semantic face."
  :group 'bv-themes)

(defface bv-face-dim '((t :inherit shadow))
  "BV dim semantic face."
  :group 'bv-themes)

(defface bv-face-faint '((t :inherit shadow))
  "BV faint semantic face."
  :group 'bv-themes)

(defface bv-face-salient '((t :inherit font-lock-keyword-face))
  "BV salient semantic face."
  :group 'bv-themes)

(defface bv-face-strong '((t :inherit bold))
  "BV strong semantic face."
  :group 'bv-themes)

(defface bv-face-critical '((t :inherit error))
  "BV critical semantic face."
  :group 'bv-themes)

(defface bv-face-success '((t :inherit success))
  "BV success semantic face."
  :group 'bv-themes)

(defface bv-face-warning '((t :inherit warning))
  "BV warning semantic face."
  :group 'bv-themes)

(defface bv-face-error '((t :inherit error))
  "BV error semantic face."
  :group 'bv-themes)

(defface bv-face-info '((t :inherit font-lock-doc-face))
  "BV informational semantic face."
  :group 'bv-themes)

(defface bv-face-link '((t :inherit link))
  "BV link semantic face."
  :group 'bv-themes)

(defface bv-face-prompt '((t :inherit minibuffer-prompt))
  "BV prompt semantic face."
  :group 'bv-themes)

(defface bv-face-keybind '((t :inherit font-lock-constant-face))
  "BV key binding semantic face."
  :group 'bv-themes)

(defface bv-face-match '((t :inherit match))
  "BV match semantic face."
  :group 'bv-themes)

(defface bv-face-highlight '((t :inherit highlight))
  "BV highlight semantic face."
  :group 'bv-themes)

(defface bv-face-secondary '((t :inherit secondary-selection))
  "BV secondary semantic face."
  :group 'bv-themes)

(defface bv-face-selection '((t :inherit region))
  "BV selection semantic face."
  :group 'bv-themes)

(defface bv-diagnostic-error '((t :inherit error))
  "BV diagnostic error face."
  :group 'bv-themes)

(defface bv-diagnostic-warning '((t :inherit warning))
  "BV diagnostic warning face."
  :group 'bv-themes)

(defface bv-diagnostic-info '((t :inherit font-lock-doc-face))
  "BV diagnostic information face."
  :group 'bv-themes)

(defface bv-diagnostic-note '((t :inherit shadow))
  "BV diagnostic note face."
  :group 'bv-themes)

(defface bv-diff-added '((t :inherit diff-added))
  "BV diff added face."
  :group 'bv-themes)

(defface bv-diff-removed '((t :inherit diff-removed))
  "BV diff removed face."
  :group 'bv-themes)

(defface bv-diff-changed '((t :inherit diff-changed))
  "BV diff changed face."
  :group 'bv-themes)

(defface bv-diff-added-refine '((t :inherit diff-refine-added))
  "BV diff added refinement face."
  :group 'bv-themes)

(defface bv-diff-removed-refine '((t :inherit diff-refine-removed))
  "BV diff removed refinement face."
  :group 'bv-themes)

(defface bv-diff-changed-refine '((t :inherit diff-changed))
  "BV diff changed refinement face."
  :group 'bv-themes)

(defface bv-ui-header-default '((t :inherit header-line))
  "BV default header-line face."
  :group 'bv-themes)

(defface bv-ui-header-muted '((t :inherit (shadow header-line)))
  "BV muted header-line face."
  :group 'bv-themes)

(defface bv-ui-header-strong '((t :inherit (bold header-line)))
  "BV strong header-line face."
  :group 'bv-themes)

(defface bv-ui-header-salient
  '((t :inherit (font-lock-keyword-face header-line)))
  "BV salient header-line face."
  :group 'bv-themes)

(defface bv-ui-header-info '((t :inherit (success header-line)))
  "BV informational header-line signal face."
  :group 'bv-themes)

(defface bv-ui-header-warning '((t :inherit (warning header-line)))
  "BV warning header-line signal face."
  :group 'bv-themes)

(defface bv-ui-header-error '((t :inherit (error header-line)))
  "BV error header-line signal face."
  :group 'bv-themes)

(defface bv-ui-header-popout '((t :inherit mode-line))
  "BV popout header-line face."
  :group 'bv-themes)

(defface bv-ui-header-critical '((t :inherit (error header-line)))
  "BV critical header-line face."
  :group 'bv-themes)

(defface bv-ui-header-inactive-default '((t :inherit mode-line-inactive))
  "BV inactive default header-line face."
  :group 'bv-themes)

(defface bv-ui-header-inactive-muted '((t :inherit (shadow mode-line-inactive)))
  "BV inactive muted header-line face."
  :group 'bv-themes)

(defface bv-ui-header-inactive-strong '((t :inherit mode-line-inactive))
  "BV inactive strong header-line face."
  :group 'bv-themes)

(defface bv-ui-header-inactive-salient '((t :inherit mode-line-inactive))
  "BV inactive salient header-line face."
  :group 'bv-themes)

(defface bv-ui-header-inactive-info '((t :inherit mode-line-inactive))
  "BV inactive informational header-line signal face."
  :group 'bv-themes)

(defface bv-ui-header-inactive-warning '((t :inherit mode-line-inactive))
  "BV inactive warning header-line signal face."
  :group 'bv-themes)

(defface bv-ui-header-inactive-error '((t :inherit mode-line-inactive))
  "BV inactive error header-line signal face."
  :group 'bv-themes)

(defface bv-ui-header-inactive-popout '((t :inherit mode-line-inactive))
  "BV inactive popout header-line face."
  :group 'bv-themes)

(defface bv-ui-header-inactive-critical '((t :inherit mode-line-inactive))
  "BV inactive critical header-line face."
  :group 'bv-themes)

(defun bv-themes-adapters--indexed (prefix roles &optional start)
  "Return face adapter specs for PREFIX numbered by ROLES.
When START is non-nil, begin numbering from that value."
  (cl-loop for role in roles
           for index from (or start 0)
           collect (list (intern (format "%s-%d" prefix index)) role)))

(defun bv-themes-adapters--terminal-range (prefix start end)
  "Return terminal color adapter specs for PREFIX from START to END."
  (cl-loop for index from start to end
           collect (list (intern (format "%s-%d" prefix index))
                         'terminal-black
                         :fg (list 'xterm-256 index))))

(defconst bv-themes-adapter-package-rules
  '((bv
     :prefixes ("bv-"))
    (core
     :faces (default fixed-pitch fixed-pitch-serif variable-pitch
             variable-pitch-text cursor fringe vertical-border border
             internal-border child-frame-border escape-glyph homoglyph
             nobreak-space region secondary-selection highlight hl-line link
             link-visited button shadow match trailing-whitespace success
             warning error bold italic bold-italic underline tooltip
             glyphless-char minibuffer-prompt line-number
             line-number-current-line line-number-major-tick
             line-number-minor-tick show-paren-match show-paren-mismatch))
    (window
     :prefixes ("window-divider"))
    (header-line
     :prefixes ("header-line"))
    (mode-line
     :prefixes ("mode-line"))
    (tab-bar
     :prefixes ("tab-bar" "tab-line"))
    (battery
     :prefixes ("battery"))
    (display-time
     :prefixes ("display-time"))
    (completion
     :prefixes ("completions" "completion-preview" "next-error"
                "compilation"))
    (search
     :faces (lazy-highlight isearch isearch-fail query-replace)
     :prefixes ("isearch-group" "anzu" "iedit"))
    (font-lock
     :prefixes ("font-lock" "elisp-shorthand"))
    (tree-sitter
     :prefixes ("tree-sitter-hl-face"))
    (whitespace
     :prefixes ("whitespace"))
    (pulse
     :prefixes ("pulse" "beacon" "bm-"))
    (eros
     :prefixes ("eros-"))
    (avy
     :prefixes ("avy" "ace-jump" "ace-window" "aw-"))
    (hydra
     :prefixes ("hydra-" "lv-"))
    (multiple-cursors
     :prefixes ("multiple-cursors" "mc/"))
    (highlight-symbol
     :prefixes ("highlight-symbol"))
    (hi-lock
     :prefixes ("hi-"))
    (xref
     :prefixes ("xref"))
    (eldoc
     :prefixes ("eldoc"))
    (diagnostics
     :prefixes ("flymake" "flycheck" "flyspell"))
    (jit-lock
     :prefixes ("jit-lock"))
    (diff
     :prefixes ("diff-" "ediff" "smerge"))
    (vc
     :prefixes ("vc-" "log-view" "diff-hl" "git-gutter"))
    (change-log
     :prefixes ("change-log-"))
    (log-edit
     :prefixes ("log-edit-"))
    (git-commit
     :prefixes ("git-commit-"))
    (magit
     :prefixes ("magit"))
    (transient
     :prefixes ("transient"))
    (outline
     :prefixes ("outline"))
    (org
     :prefixes ("org-" "org-modern" "org-ql" "org-roam"
                "org-super-agenda"))
    (markdown
     :prefixes ("markdown"))
    (rst
     :prefixes ("rst"))
    (dired
     :prefixes ("dired" "diredfl"))
    (buffer-list
     :prefixes ("ibuffer" "buffer-menu"))
    (bookmark
     :prefixes ("bookmark"))
    (package
     :prefixes ("package"))
    (custom
     :prefixes ("custom" "widget"))
    (info
     :prefixes ("info" "Info-"))
    (help
     :prefixes ("help" "helpful" "apropos" "Man-" "woman"))
    (doc-view
     :prefixes ("doc-view"))
    (shr-eww
     :prefixes ("shr" "eww"))
    (nov
     :prefixes ("nov"))
    (vertico
     :prefixes ("vertico"))
    (orderless
     :prefixes ("orderless"))
    (consult
     :prefixes ("consult"))
    (marginalia
     :prefixes ("marginalia"))
    (corfu
     :prefixes ("corfu"))
    (company
     :prefixes ("company"))
    (cape
     :prefixes ("cape"))
    (which-key
     :prefixes ("which-key"))
    (embark
     :prefixes ("embark"))
    (icomplete
     :prefixes ("icomplete"))
    (ido
     :prefixes ("ido"))
    (eglot
     :prefixes ("eglot"))
    (lsp
     :prefixes ("lsp-"))
    (dape
     :prefixes ("dape"))
    (breakpoint
     :prefixes ("breakpoint"))
    (combobulate
     :prefixes ("combobulate"))
    (envrc
     :prefixes ("envrc"))
    (keycast
     :prefixes ("keycast"))
    (perspective
     :prefixes ("persp"))
    (tempel
     :prefixes ("tempel"))
    (vundo
     :prefixes ("vundo"))
    (olivetti
     :prefixes ("olivetti"))
    (comint
     :prefixes ("comint"))
    (eshell
     :prefixes ("eshell"))
    (terminal
     :faces (term)
     :prefixes ("term-" "term-color" "ansi-color" "vterm-color" "eat-term"
                "eat-shell"))
    (biblio
     :prefixes ("biblio"))
    (calendar
     :prefixes ("calendar" "diary" "holiday"))
    (elfeed
     :prefixes ("elfeed"))
    (citar
     :prefixes ("citar"))
    (mail
     :prefixes ("ebdb" "message" "mu4e" "mm-uu"))
    (gnus
     :prefixes ("gnus-"))
    (epa
     :prefixes ("epa"))
    (ert
     :prefixes ("ert"))
    (latex
     :faces (subscript superscript)
     :prefixes ("font-latex" "TeX-" "tex-" "preview"))
    (c-mode
     :prefixes ("c-"))
    (shell-script
     :prefixes ("sh-" "shell-highlight"))
    (sgml
     :prefixes ("sgml"))
    (sly
     :prefixes ("sly"))
    (lispy
     :prefixes ("lispy-"))
    (edebug
     :prefixes ("edebug-"))
    (edit-indirect
     :prefixes ("edit-indirect"))
    (llama
     :prefixes ("llama-"))
    (which-func
     :faces (which-func))
    (rst-extra
     :prefixes ("rst-"))
    (misc-ui
     :faces (abbrev-table-name blink-matching-paren-offscreen
             browse-url-button confusingly-reordered edmacro-label ffap
             file-name-shadow fill-column-indicator grep-heading
             gud-highlight-current-line-face hexl-address-region
             hexl-ascii-region icon icon-button kmacro-menu-flagged
             kmacro-menu-mark kmacro-menu-marked menu mm-command-output
             mouse mouse-drag-and-drop-region nobreak-hyphen
             read-multiple-choice-face scroll-bar separator-line
             show-paren-match-expression table-cell
             tabulated-list-fake-header tool-bar tty-menu-disabled-face
             tty-menu-enabled-face tty-menu-selected-face
             widget-unselected world-clock-label)
     :prefixes ("so-long" "treesit-explorer"))
    (rainbow-delimiters
     :prefixes ("rainbow-delimiters"))
    (smartparens
     :prefixes ("smartparens" "sp-" "paren-face"
                "highlight-parentheses"))
    (nerd-icons
     :prefixes ("nerd-icons"))
    (dashboard
     :prefixes ("dashboard" "doom-dashboard"))
    (solaire
     :prefixes ("solaire")))
  "Rules that assign adapter faces to their package owner.")

(defconst bv-themes-adapter-specs
  (append
   '((default default)
     (fixed-pitch fixed-pitch)
     (fixed-pitch-serif fixed-pitch)
     (variable-pitch variable-pitch)
     (variable-pitch-text variable-pitch-text)
     (cursor cursor)
     (fringe fringe)
     (vertical-border border)
     (window-divider border)
     (window-divider-first-pixel border)
     (window-divider-last-pixel border)
     (border border)
     (internal-border border)
     (child-frame-border border)
     (minibuffer-prompt prompt)
     (escape-glyph escape)
     (homoglyph escape)
     (nobreak-space escape)
     (region region)
     (secondary-selection secondary-selection)
     (highlight highlight)
     (hl-line hl-line)
     (line-number line-number)
     (line-number-current-line line-number-current)
     (link link)
     (link-visited link-visited)
     (button button)
     (shadow shadow)
     (match match)
     (lazy-highlight search-lazy)
     (isearch search-current)
     (isearch-fail error-subtle)
     (query-replace search-current)
     (trailing-whitespace trailing)
     (show-paren-match paren)
     (show-paren-mismatch critical-block)
     (success success)
     (warning warning)
     (error error)
     (bold bold)
     (italic italic)
     (bold-italic bold :slant italic)
     (underline link)
     (header-line header-default)
     (header-line-highlight header-salient)
     (mode-line mode-line-active)
     (mode-line-active mode-line-active)
     (mode-line-inactive mode-line-inactive)
     (mode-line-buffer-id mode-line-accent)
     (mode-line-emphasis mode-line-accent)
     (mode-line-highlight highlight)
     (tab-bar tab-bar)
     (tab-bar-tab tab-current)
     (tab-bar-tab-inactive tab-other)
     (tab-line tab-bar)
     (tab-line-tab tab-current)
     (tab-line-tab-current tab-current)
     (tab-line-tab-inactive tab-other)
     (tab-line-highlight highlight)
     (tooltip tooltip)
     (glyphless-char faint)
     (help-key-binding keybind)
     (completions-common-part completion-match-0)
     (completions-first-difference completion-match-1)
     (completions-annotations completion-annotation)
     (completions-highlight completion-current)
     (completion-preview completion-annotation)
     (completion-preview-common completion-match-0)
     (completion-preview-exact completion-match-1)
     (next-error match)
     (next-error-message highlight)
     (compilation-column-number dim)
     (compilation-line-number salient)
     (compilation-mode-line-exit success)
     (compilation-mode-line-fail error)
     (compilation-mode-line-run warning)
     (compilation-info info)
     (compilation-warning warning)
     (compilation-error error)
     (font-lock-comment-face syntax-comment)
     (font-lock-comment-delimiter-face syntax-comment)
     (font-lock-doc-face syntax-doc)
     (font-lock-doc-markup-face syntax-property)
     (font-lock-string-face syntax-string)
     (font-lock-regexp-grouping-backslash syntax-escape)
     (font-lock-regexp-grouping-construct syntax-regexp)
     (font-lock-keyword-face syntax-keyword)
     (font-lock-builtin-face syntax-builtin)
     (font-lock-function-name-face syntax-function)
     (font-lock-variable-name-face syntax-variable)
     (font-lock-variable-use-face syntax-variable-use)
     (font-lock-property-name-face syntax-property)
     (font-lock-property-use-face syntax-property)
     (font-lock-constant-face syntax-constant)
     (font-lock-number-face syntax-number)
     (font-lock-type-face syntax-type)
     (font-lock-operator-face syntax-operator)
     (font-lock-preprocessor-face syntax-preprocessor)
     (font-lock-negation-char-face syntax-operator)
     (font-lock-escape-face syntax-escape)
     (font-lock-warning-face syntax-warning)
     (font-lock-bracket-face syntax-bracket)
     (font-lock-delimiter-face syntax-delimiter)
     (tree-sitter-hl-face:attribute syntax-property)
     (tree-sitter-hl-face:comment syntax-comment)
     (tree-sitter-hl-face:constant syntax-constant)
     (tree-sitter-hl-face:constant.builtin syntax-builtin)
     (tree-sitter-hl-face:constructor syntax-function)
     (tree-sitter-hl-face:doc syntax-doc)
     (tree-sitter-hl-face:embedded syntax-string)
     (tree-sitter-hl-face:function syntax-function)
     (tree-sitter-hl-face:function.builtin syntax-builtin)
     (tree-sitter-hl-face:function.call syntax-function)
     (tree-sitter-hl-face:keyword syntax-keyword)
     (tree-sitter-hl-face:label syntax-property)
     (tree-sitter-hl-face:number syntax-number)
     (tree-sitter-hl-face:operator syntax-operator)
     (tree-sitter-hl-face:property syntax-property)
     (tree-sitter-hl-face:punctuation syntax-delimiter)
     (tree-sitter-hl-face:string syntax-string)
     (tree-sitter-hl-face:string.special syntax-escape)
     (tree-sitter-hl-face:tag syntax-keyword)
     (tree-sitter-hl-face:type syntax-type)
     (tree-sitter-hl-face:type.builtin syntax-builtin)
     (tree-sitter-hl-face:variable syntax-variable)
     (tree-sitter-hl-face:variable.builtin syntax-builtin)
     (tree-sitter-hl-face:variable.parameter syntax-variable)
     (whitespace-space faint)
     (whitespace-hspace faint)
     (whitespace-tab warning-subtle)
     (whitespace-newline faint)
     (whitespace-trailing trailing)
     (whitespace-line warning-subtle)
     (whitespace-space-after-tab warning-subtle)
     (whitespace-space-before-tab warning-subtle)
     (whitespace-indentation warning-subtle)
     (whitespace-big-indent warning-subtle)
     (whitespace-empty error-subtle)
     (whitespace-missing-newline-at-eof warning-subtle)
     (pulse-highlight-start-face highlight)
     (pulse-highlight-face highlight)
     (pulse-highlight-region-face region)
     (pulse-momentary-highlight-one-line hl-line)
     (pulse-momentary-highlight-region region)
     (bm-face highlight)
     (bm-fringe-face salient)
     (beacon-fallback-background highlight)
     (eros-result-overlay-face success)
     (avy-lead-face mode-line-accent)
     (avy-lead-face-0 success-subtle)
     (avy-lead-face-1 warning-subtle)
     (avy-lead-face-2 info-subtle)
     (avy-background-face faint)
     (ace-jump-face-foreground mode-line-accent)
     (ace-jump-face-background faint)
     (ace-window-face mode-line-accent)
     (hydra-face-amaranth warning)
     (hydra-face-blue info)
     (hydra-face-pink warning)
     (hydra-face-red error)
     (hydra-face-teal success)
     (lv-separator border)
     (multiple-cursors-cursor cursor)
     (mc/cursor-bar-face cursor)
     (mc/cursor-face cursor)
     (highlight-symbol-face match)
     (hi-yellow warning-subtle)
     (hi-pink error-subtle)
     (hi-green success-subtle)
     (hi-blue info-subtle)
     (hi-salmon error-subtle)
     (hi-aquamarine info-subtle)
     (hi-black-b highlight)
     (hi-blue-b info-subtle)
     (hi-green-b success-subtle)
     (hi-red-b error-subtle)
     (hi-black-hb highlight)
     (isearch-group-1 search-current)
     (isearch-group-2 search)
     (anzu-mode-line mode-line-accent)
     (anzu-match-1 search)
     (anzu-match-2 search-lazy)
     (anzu-match-3 match)
     (anzu-replace-to search-current)
     (anzu-replace-highlight search-current)
     (iedit-occurrence search)
     (iedit-read-only-occurrence warning-subtle)
     (xref-file-header diff-file-header)
     (xref-line-number line-number-current)
     (xref-match match)
     (xref-backend-header dim)
     (eldoc-highlight-function-argument salient)
     (eldoc-box-body default-plain)
     (eldoc-box-border border)
     (eldoc-box-markdown-separator border)
     (eldoc-box-highlight highlight)
     (flymake-error diagnostic-error)
     (flymake-warning diagnostic-warning)
     (flymake-note diagnostic-note)
     (flymake-end-of-line-diagnostics-face diagnostic-info :height 0.85)
     (flycheck-error diagnostic-error)
     (flycheck-warning diagnostic-warning)
     (flycheck-info diagnostic-info)
     (flycheck-fringe-error error)
     (flycheck-fringe-warning warning)
     (flycheck-fringe-info info)
     (flycheck-error-list-error error)
     (flycheck-error-list-warning warning)
     (flycheck-error-list-info info)
     (flyspell-duplicate diagnostic-warning)
     (flyspell-incorrect diagnostic-error)
     (jit-lock-changed warning-subtle)
     (jit-lock-defer-time error)
     (jit-lock-function-call syntax-function)
     (jit-lock-stealth-time dim)
     (diff-header diff-header)
     (diff-file-header diff-file-header)
     (diff-index diff-file-header)
     (diff-hunk-header diff-header)
     (diff-function diff-header)
     (diff-context diff-context)
     (diff-added diff-added)
     (diff-removed diff-removed)
     (diff-changed diff-changed)
     (diff-refine-added diff-added-refine)
     (diff-refine-removed diff-removed-refine)
     (diff-refine-changed diff-changed-refine)
     (diff-indicator-added vc-added)
     (diff-indicator-removed vc-removed)
     (diff-indicator-changed vc-changed)
     (ediff-current-diff-A diff-removed)
     (ediff-current-diff-B diff-added)
     (ediff-current-diff-C diff-changed)
     (ediff-current-diff-Ancestor diff-changed)
     (ediff-even-diff-A diff-context)
     (ediff-even-diff-B diff-context)
     (ediff-even-diff-C diff-context)
     (ediff-even-diff-Ancestor diff-context)
     (ediff-fine-diff-A diff-removed-refine)
     (ediff-fine-diff-B diff-added-refine)
     (ediff-fine-diff-C diff-changed-refine)
     (ediff-fine-diff-Ancestor diff-changed-refine)
     (ediff-odd-diff-A diff-context)
     (ediff-odd-diff-B diff-context)
     (ediff-odd-diff-C diff-context)
     (ediff-odd-diff-Ancestor diff-context)
     (smerge-base diff-changed)
     (smerge-lower diff-added)
     (smerge-upper diff-removed)
     (smerge-markers diff-header)
     (smerge-refined-added diff-added-refine)
     (smerge-refined-changed diff-changed-refine)
     (smerge-refined-removed diff-removed-refine)
     (log-view-file diff-file-header)
     (log-view-message salient)
     (log-view-commit-body default-plain)
     (log-view-commit-body-branch salient)
     (vc-conflict-state error)
     (vc-edited-state vc-changed)
     (vc-locally-added-state vc-added)
     (vc-locked-state warning)
     (vc-missing-state error)
     (vc-needs-update-state warning)
     (vc-removed-state vc-removed)
     (vc-state-base default-plain)
     (vc-up-to-date-state success)
     (diff-hl-change vc-changed)
     (diff-hl-delete vc-removed)
     (diff-hl-insert vc-added)
     (git-gutter:added vc-added)
     (git-gutter:deleted vc-removed)
     (git-gutter:modified vc-changed)
     (git-gutter+-added vc-added)
     (git-gutter+-deleted vc-removed)
     (git-gutter+-modified vc-changed)
     (git-gutter-fr:added vc-added)
     (git-gutter-fr:deleted vc-removed)
     (git-gutter-fr:modified vc-changed)
     (change-log-acknowledgment dim)
     (change-log-conditionals syntax-keyword)
     (change-log-date dim)
     (change-log-email link)
     (change-log-file diff-file-header)
     (change-log-function syntax-function)
     (change-log-list keybind)
     (change-log-name syntax-function)
     (log-edit-header heading-4)
     (log-edit-headers-separator border)
     (log-edit-summary heading-4)
     (log-edit-unknown-header warning)
     (git-commit-comment-action warning)
     (git-commit-comment-branch-local success)
     (git-commit-comment-branch-remote info)
     (git-commit-comment-detached warning)
     (git-commit-comment-file diff-file-header)
     (git-commit-comment-heading heading-4)
     (git-commit-keyword syntax-keyword)
     (git-commit-nonempty-second-line error)
     (git-commit-overlong-summary warning)
     (git-commit-summary heading-4)
     (git-commit-trailer-token syntax-property)
     (git-commit-trailer-value syntax-string)
     (magit-section-heading heading-3 :weight semibold)
     (magit-section-heading-selection completion-current)
     (magit-section-highlight highlight)
     (magit-diff-context diff-context)
     (magit-diff-context-highlight highlight)
     (magit-diff-file-heading diff-file-header)
     (magit-diff-file-heading-highlight diff-file-header)
     (magit-diff-file-heading-selection completion-current)
     (magit-diff-hunk-heading diff-header)
     (magit-diff-hunk-heading-highlight diff-header)
     (magit-diff-hunk-heading-selection completion-current)
     (magit-diff-added diff-added)
     (magit-diff-added-highlight diff-added)
     (magit-diff-removed diff-removed)
     (magit-diff-removed-highlight diff-removed)
     (magit-diff-base diff-changed)
     (magit-diff-base-highlight diff-changed)
     (magit-diff-our diff-removed)
     (magit-diff-our-highlight diff-removed)
     (magit-diff-their diff-added)
     (magit-diff-their-highlight diff-added)
     (magit-diff-lines-boundary critical-block)
     (magit-diff-lines-heading diff-header)
     (magit-diff-conflict-heading critical-block)
     (magit-diff-conflict-heading-highlight critical-block)
     (magit-diff-hunk-region region)
     (magit-diff-whitespace-warning trailing)
     (magit-diff-revision-summary dim)
     (magit-diff-revision-summary-highlight highlight)
     (magit-diffstat-added vc-added)
     (magit-diffstat-removed vc-removed)
     (magit-bisect-bad error)
     (magit-bisect-good success)
     (magit-bisect-skip warning)
     (magit-branch-current salient)
     (magit-branch-local success)
     (magit-branch-remote info)
     (magit-branch-remote-head info)
     (magit-branch-upstream success)
     (magit-branch-warning warning)
     (magit-blame-date dim)
     (magit-blame-dimmed faint)
     (magit-blame-hash dim)
     (magit-blame-heading heading-4)
     (magit-blame-highlight highlight)
     (magit-blame-margin dim)
     (magit-blame-name syntax-function)
     (magit-blame-summary default-plain)
     (magit-cherry-equivalent success)
     (magit-cherry-unmatched warning)
     (magit-dimmed dim)
     (magit-filename diff-file-header)
     (magit-hash dim)
     (magit-head salient)
     (magit-header-line header-strong)
     (magit-header-line-key keybind)
     (magit-header-line-log-select heading-4)
     (magit-keyword syntax-keyword)
     (magit-keyword-squash warning)
     (magit-left-margin dim)
     (magit-log-author syntax-function)
     (magit-log-date dim)
     (magit-log-graph dim)
     (magit-mode-line-process mode-line-accent)
     (magit-mode-line-process-error error)
     (magit-process-ng error)
     (magit-process-ok success)
     (magit-refname link-muted)
     (magit-refname-pullreq info)
     (magit-refname-stash warning)
     (magit-refname-wip warning)
     (magit-reflog-amend warning)
     (magit-reflog-checkout info)
     (magit-reflog-cherry-pick success)
     (magit-reflog-commit success)
     (magit-reflog-merge success)
     (magit-reflog-other dim)
     (magit-reflog-rebase warning)
     (magit-reflog-remote info)
     (magit-reflog-reset error)
     (magit-section-child-count dim)
     (magit-section-secondary-heading heading-4 :weight semibold)
     (magit-sequence-done success)
     (magit-sequence-drop error)
     (magit-sequence-exec info)
     (magit-sequence-head salient)
     (magit-sequence-onto dim)
     (magit-sequence-part warning)
     (magit-sequence-pick success)
     (magit-sequence-stop error)
     (magit-signature-bad error)
     (magit-signature-error error)
     (magit-signature-expired warning)
     (magit-signature-expired-key warning)
     (magit-signature-good success)
     (magit-signature-revoked error)
     (magit-signature-untrusted warning)
     (magit-tag warning)
     (transient-heading heading-4)
     (transient-key keybind)
     (transient-argument warning)
     (transient-value syntax-string)
     (transient-inactive-value faint)
     (transient-unreachable faint)
     (transient-unreachable-key faint)
     (transient-enabled-suffix success)
     (transient-disabled-suffix error)
     (transient-mismatched-key error)
     (transient-nonstandard-key warning)
     (transient-higher-level warning)
     (transient-separator border)
     (outline-1 heading-1)
     (outline-2 heading-2)
     (outline-3 heading-3)
     (outline-4 heading-4)
     (outline-5 heading-5)
     (outline-6 heading-6)
     (outline-7 heading-7)
     (outline-8 heading-8)
     (org-document-title prose-title)
     (org-document-info prose-subtitle)
     (org-document-info-keyword prose-metadata)
     (org-level-1 heading-1)
     (org-level-2 heading-2)
     (org-level-3 heading-3)
     (org-level-4 heading-4)
     (org-level-5 heading-5)
     (org-level-6 heading-6)
     (org-level-7 heading-7)
     (org-level-8 heading-8)
     (org-block prose-block)
     (org-block-begin-line prose-block-begin)
     (org-block-end-line prose-block-begin)
     (org-code prose-code)
     (org-verbatim prose-verbatim)
     (org-indent faint)
     (org-table prose-table)
     (org-formula syntax-string)
     (org-meta-line prose-metadata)
     (org-special-keyword prose-metadata)
     (org-property-value prose-metadata-value)
     (org-drawer prose-metadata)
     (org-tag dim)
     (org-date link-muted)
     (org-footnote link)
     (org-link link)
     (org-list-dt salient)
     (org-checkbox keybind)
     (org-checkbox-statistics-done success)
     (org-checkbox-statistics-todo warning)
     (org-todo prose-todo)
     (org-done prose-done)
     (org-headline-done dim)
     (org-priority critical)
     (org-warning warning)
     (org-agenda-structure heading-2)
     (org-agenda-date heading-4)
     (org-agenda-date-today heading-3)
     (org-agenda-date-weekend dim)
     (org-agenda-done dim)
     (org-agenda-dimmed-todo-face dim)
     (org-agenda-calendar-event info)
     (org-agenda-calendar-sexp info)
     (org-agenda-clocking warning-subtle)
     (org-agenda-column-dateline highlight)
     (org-agenda-current-time salient)
     (org-agenda-filter-category salient)
     (org-agenda-filter-effort warning)
     (org-agenda-filter-regexp warning)
     (org-agenda-filter-tags salient)
     (org-agenda-restriction-lock warning-subtle)
     (org-archived dim)
     (org-scheduled success)
     (org-scheduled-previously warning)
     (org-scheduled-today info)
     (org-upcoming-deadline warning)
     (org-time-grid dim)
     (org-sexp-date syntax-string)
     (org-cite link-muted)
     (org-cite-key link)
     (org-modern-date-active info-subtle)
     (org-modern-date-inactive dim)
     (org-modern-block-name prose-block-begin)
     (org-modern-done prose-done)
     (org-modern-habit warning-subtle)
     (org-modern-horizontal-rule border)
     (org-modern-internal-target link-muted)
     (org-modern-label keybind)
     (org-modern-priority critical)
     (org-modern-progress-complete success)
     (org-modern-progress-incomplete warning)
     (org-modern-radio-target link)
     (org-modern-symbol keybind)
     (org-modern-tag dim)
     (org-modern-time-active info)
     (org-modern-time-inactive dim)
     (org-modern-todo prose-todo)
     (org-ql-view-due-date warning)
     (org-ql-view-habit-overdue-face error)
     (org-ql-view-habit-ready-face warning)
     (org-ql-view-habit-done-face success)
     (org-ql-view-habit-clear-face dim)
     (org-roam-link link)
     (org-roam-link-current salient)
     (org-roam-link-invalid error)
     (org-super-agenda-header heading-3)
     (markdown-header-face-1 heading-1)
     (markdown-header-delimiter-face prose-metadata)
     (markdown-header-face-2 heading-2)
     (markdown-header-face-3 heading-3)
     (markdown-header-face-4 heading-4)
     (markdown-header-face-5 heading-5)
     (markdown-header-face-6 heading-6)
     (markdown-header-face heading-3)
     (markdown-header-rule-face border)
     (markdown-code-face prose-code)
     (markdown-inline-code-face prose-code)
     (markdown-pre-face prose-block)
     (markdown-blockquote-face prose-block)
     (markdown-comment-face syntax-comment)
     (markdown-footnote-marker-face link)
     (markdown-footnote-text-face dim)
     (markdown-gfm-checkbox-face keybind)
     (markdown-highlight-face highlight)
     (markdown-highlighting-face highlight)
     (markdown-hr-face border)
     (markdown-html-attr-name-face syntax-property)
     (markdown-html-attr-value-face syntax-string)
     (markdown-html-entity-face syntax-constant)
     (markdown-html-tag-delimiter-face syntax-delimiter)
     (markdown-html-tag-name-face syntax-keyword)
     (markdown-language-info-face dim)
     (markdown-line-break-face warning-subtle)
     (markdown-url-face link-muted)
     (markdown-link-face link)
     (markdown-link-title-face prose-metadata)
     (markdown-missing-link-face error)
     (markdown-plain-url-face link-muted)
     (markdown-reference-face link-muted)
     (markdown-list-face keybind)
     (markdown-metadata-key-face prose-metadata)
     (markdown-metadata-value-face prose-metadata-value)
     (markdown-language-keyword-face syntax-keyword)
     (markdown-markup-face prose-metadata)
     (markdown-bold-face bold)
     (markdown-italic-face italic)
     (markdown-math-face syntax-string)
     (markdown-strike-through-face dim :strike-through t)
     (markdown-table-face prose-table)
     (rst-level-1 heading-1)
     (rst-level-2 heading-2)
     (rst-level-3 heading-3)
     (rst-level-4 heading-4)
     (rst-level-5 heading-5)
     (rst-level-6 heading-6)
     (dired-directory heading-4)
     (dired-flagged error)
     (dired-header heading-3)
     (dired-ignored dim)
     (dired-mark success)
     (dired-marked warning-subtle)
     (dired-perm-write warning)
     (dired-symlink link)
     (dired-warning warning)
     (dired-broken-symlink error)
     (diredfl-dir-name heading-4)
     (diredfl-dir-heading heading-3)
     (diredfl-file-name default-plain)
     (diredfl-file-suffix dim)
     (diredfl-compressed-file-name warning)
     (diredfl-compressed-file-suffix warning)
     (diredfl-date-time dim)
     (diredfl-deletion error)
     (diredfl-deletion-file-name error)
     (diredfl-exec-priv warning)
     (diredfl-executable-tag warning)
     (diredfl-flag-mark success)
     (diredfl-flag-mark-line success-subtle)
     (diredfl-ignored-file-name dim)
     (diredfl-link-priv link)
     (diredfl-no-priv dim)
     (diredfl-number info)
     (diredfl-other-priv info)
     (diredfl-rare-priv warning)
     (diredfl-read-priv success)
     (diredfl-symlink link)
     (diredfl-write-priv warning)
     (ibuffer-title heading-3)
     (ibuffer-filter-group-name heading-4)
     (ibuffer-marked warning)
     (ibuffer-locked error)
     (ibuffer-deletion error)
     (ibuffer-special-buffer salient)
     (ibuffer-read-only dim)
     (ibuffer-modified warning)
     (ibuffer-help-buffer info)
     (ibuffer-dired-buffer heading-4)
     (ibuffer-occur-match match)
     (buffer-menu-buffer strong)
     (buffer-menu-delete error)
     (buffer-menu-flagged warning)
     (buffer-menu-star-buffer salient)
     (bookmark-face salient)
     (bookmark-menu-bookmark link)
     (bookmark-menu-heading heading-3)
     (package-name link)
     (package-description default-plain)
     (package-help-section-name heading-4)
     (package-status-avail-obso warning)
     (package-status-available info)
     (package-status-built-in success)
     (package-status-dependency dim)
     (package-status-disabled dim)
     (package-status-external info)
     (package-status-from-source info)
     (package-status-held warning)
     (package-status-incompat error)
     (package-status-installed success)
     (package-status-new info)
     (package-status-unsigned warning)
     (custom-button button)
     (custom-button-mouse button)
     (custom-button-pressed mode-line-accent)
     (custom-button-pressed-unraised mode-line-accent)
     (custom-button-unraised button)
     (custom-changed warning)
     (custom-comment default-plain)
     (custom-comment-tag syntax-comment)
     (custom-documentation default-plain)
     (custom-face-tag heading-4)
     (custom-group-subtitle heading-4)
     (custom-group-tag heading-3)
     (custom-group-tag-1 heading-4)
     (custom-invalid error)
     (custom-link link)
     (custom-modified warning)
     (custom-rogue error)
     (custom-saved success)
     (custom-set success)
     (custom-state info)
     (custom-themed success)
     (custom-variable-button button)
     (custom-variable-obsolete warning)
     (custom-variable-tag heading-4)
     (custom-visibility link)
     (widget-button button)
     (widget-button-pressed mode-line-accent)
     (widget-documentation default-plain)
     (widget-field completion)
     (widget-inactive dim)
     (widget-single-line-field completion)
     (info-header-node heading-4)
     (info-header-xref link)
     (info-index-match match)
     (Info-quoted prose-code)
     (info-menu-header heading-4)
     (info-menu-star salient)
     (info-node link)
     (info-title-1 heading-1)
     (info-title-2 heading-2)
     (info-title-3 heading-3)
     (info-title-4 heading-4)
     (info-xref link)
     (info-xref-visited link-visited)
     (help-argument-name syntax-variable)
     (help-for-help-header heading-3)
     (helpful-heading heading-3)
     (helpful-link link)
     (apropos-button link)
     (apropos-function-button syntax-function)
     (apropos-keybinding keybind)
     (apropos-misc-button salient)
     (apropos-property syntax-property)
     (apropos-symbol syntax-variable)
     (apropos-user-option-button syntax-variable)
     (Man-overstrike heading-4)
     (Man-underline link)
     (woman-bold heading-4)
     (woman-italic italic)
     (woman-unknown error)
     (doc-view-svg-face prose-block)
     (shr-link link)
     (shr-selected-link link-visited)
     (shr-abbreviation syntax-property)
     (shr-code prose-code)
     (shr-h1 heading-1)
     (shr-h2 heading-2)
     (shr-h3 heading-3)
     (shr-h4 heading-4)
     (shr-h5 heading-5)
     (shr-h6 heading-6)
     (shr-text default-plain)
     (shr-strike-through dim)
     (shr-sliced-image default-plain)
     (eww-valid-certificate success)
     (eww-invalid-certificate error)
     (eww-form-submit button)
     (eww-form-checkbox button)
     (eww-form-file button)
     (eww-form-select button)
     (eww-form-text completion)
     (eww-form-textarea completion)
     (nov-header-line header-default)
     (nov-title heading-2)
     (nov-metadata dim)
     (vertico-current completion-current)
     (vertico-group-title heading-4)
     (vertico-group-separator border)
     (vertico-multiline completion)
     (vertico-quick1 mode-line-accent)
     (vertico-quick2 warning)
     (orderless-match-face-0 completion-match-0)
     (orderless-match-face-1 completion-match-1)
     (orderless-match-face-2 completion-match-2)
     (orderless-match-face-3 completion-match-3)
     (consult-file link)
     (consult-bookmark link)
     (consult-buffer strong)
     (consult-preview-match match)
     (consult-highlight-match match)
     (consult-highlight-mark match)
     (consult-highlight-narrow completion-match)
     (consult-async-running warning)
     (consult-async-failed error)
     (consult-async-split warning)
     (consult-async-finished success)
     (consult-line-number-prefix dim)
     (consult-line-number-wrapped dim)
     (consult-separator border)
     (marginalia-archive warning)
     (marginalia-char syntax-string)
     (marginalia-date dim)
     (marginalia-documentation prose-metadata)
     (marginalia-file-name default-plain)
     (marginalia-file-owner dim)
     (marginalia-file-priv-dir special)
     (marginalia-file-priv-exec info)
     (marginalia-file-priv-link link)
     (marginalia-file-priv-no dim)
     (marginalia-file-priv-other info)
     (marginalia-file-priv-rare warning)
     (marginalia-file-priv-read success)
     (marginalia-file-priv-write error)
     (marginalia-function syntax-function)
     (marginalia-installed success)
     (marginalia-key keybind)
     (marginalia-lighter dim)
     (marginalia-list dim)
     (marginalia-mode salient)
     (marginalia-modified warning)
     (marginalia-null dim)
     (marginalia-number syntax-number)
     (marginalia-off dim)
     (marginalia-on success)
     (marginalia-size dim)
     (marginalia-string syntax-string)
     (marginalia-symbol syntax-variable)
     (marginalia-true success)
     (marginalia-type syntax-type)
     (marginalia-value syntax-constant)
     (marginalia-version info)
     (corfu-default completion)
     (corfu-current completion-current)
     (corfu-border completion-border)
     (corfu-bar completion-scrollbar-thumb)
     (corfu-annotations completion-annotation)
     (corfu-deprecated dim)
     (corfu-popupinfo completion-popup)
     (corfu-popupinfo-shell prompt)
     (corfu-popupinfo-scrollbar completion-scrollbar-thumb)
     (corfu-echo completion-annotation)
     (corfu-quick1 mode-line-accent)
     (corfu-quick2 warning)
     (company-tooltip completion)
     (company-tooltip-selection completion-current)
     (company-tooltip-common completion-match-0)
     (company-tooltip-common-selection completion-match-1)
     (company-tooltip-annotation completion-annotation)
     (company-tooltip-annotation-selection completion-annotation)
     (company-tooltip-deprecated dim)
     (company-tooltip-mouse highlight)
     (company-tooltip-scrollbar-thumb completion-scrollbar-thumb)
     (company-tooltip-scrollbar-track completion-scrollbar-track)
     (company-echo completion-annotation)
     (company-echo-common completion-match-0)
     (company-preview completion)
     (company-preview-common completion-match-0)
     (company-preview-search search)
     (company-scrollbar-bg completion-scrollbar-track)
     (company-scrollbar-fg completion-scrollbar-thumb)
     (company-template-field region)
     (company-tooltip-quick-access keybind)
     (company-tooltip-quick-access-selection completion-current)
     (company-tooltip-search search)
     (company-tooltip-search-selection search-current)
     (cape-keyword completion-match-0)
     (which-key-key-face keybind)
     (which-key-command-description-face default-plain)
     (which-key-group-description-face heading-4)
     (which-key-local-map-description-face info)
     (which-key-note-face dim)
     (which-key-separator-face border)
     (which-key-special-key-face warning)
     (embark-keybinding keybind)
     (embark-target mode-line-accent)
     (embark-collect-annotation completion-annotation)
     (embark-collect-marked completion-current)
     (embark-collect-group-title heading-4)
     (embark-collect-group-separator border)
     (icomplete-selected-match completion-current)
     (icomplete-section heading-4)
     (ido-first-match completion-match)
     (ido-only-match success)
     (ido-subdir heading-4)
     (ido-virtual info)
     (ido-incomplete-regexp error)
     (icomplete-first-match completion-current)
     (eglot-highlight-symbol-face match)
     (eglot-mode-line mode-line-accent)
     (eglot-diagnostic-tag-deprecated-face dim)
     (eglot-diagnostic-tag-unnecessary-face dim)
     (eglot-inlay-hint-face dim)
     (eglot-type-hierarchy-base salient)
     (eglot-type-hierarchy-derived salient)
     (lsp-face-highlight-read match)
     (lsp-face-highlight-textual match)
     (lsp-face-highlight-write match)
     (lsp-face-rename completion-current)
     (lsp-face-semhl-constant syntax-constant)
     (lsp-face-semhl-variable syntax-variable)
     (lsp-face-semhl-function syntax-function)
     (lsp-face-semhl-method syntax-function)
     (lsp-face-semhl-class syntax-type)
     (lsp-face-semhl-interface syntax-type)
     (lsp-face-semhl-enum syntax-type)
     (lsp-face-semhl-type-parameter syntax-type)
     (lsp-face-semhl-property syntax-property)
     (lsp-face-semhl-namespace syntax-builtin)
     (lsp-face-semhl-keyword syntax-keyword)
     (lsp-face-semhl-operator syntax-operator)
     (lsp-ui-doc-background popup)
     (lsp-ui-doc-header heading-4)
     (lsp-ui-doc-url link)
     (lsp-ui-peek-header header-strong)
     (lsp-ui-peek-footer header-default)
     (lsp-ui-peek-list highlight)
     (lsp-ui-peek-peek highlight)
     (lsp-ui-peek-selection completion-current)
     (lsp-ui-peek-filename diff-file-header)
     (lsp-ui-peek-line-number line-number)
     (lsp-ui-peek-highlight match)
     (lsp-ui-sideline-code-action warning)
     (lsp-ui-sideline-current-symbol salient)
     (lsp-ui-sideline-symbol info)
     (lsp-ui-sideline-symbol-info dim)
     (dape-breakpoint-face error)
     (dape-expression-face warning)
     (dape-log-face dim)
     (dape-repl-stdout-face success)
     (dape-repl-stderr-face error)
     (dape-repl-error-face error)
     (dape-repl-info-face info)
     (comint-highlight-input prompt)
     (comint-highlight-prompt prompt)
     (comint-highlight-matching-input match)
     (eshell-prompt prompt)
     (eshell-ls-archive warning)
     (eshell-ls-backup dim)
     (eshell-ls-clutter dim)
     (eshell-ls-directory heading-4)
     (eshell-ls-executable warning)
     (eshell-ls-missing error)
     (eshell-ls-product syntax-string)
     (eshell-ls-product-lock warning)
     (eshell-ls-readonly dim)
     (eshell-ls-special salient)
     (eshell-ls-symlink link)
     (eshell-ls-unreadable error)
     (term terminal-default)
     (term-color-black terminal-black)
     (term-color-red terminal-red)
     (term-color-green terminal-green)
     (term-color-yellow terminal-yellow)
     (term-color-blue terminal-blue)
     (term-color-magenta terminal-magenta)
     (term-color-cyan terminal-cyan)
     (term-color-white terminal-white)
     (ansi-color-black terminal-black)
     (ansi-color-red terminal-red)
     (ansi-color-green terminal-green)
     (ansi-color-yellow terminal-yellow)
     (ansi-color-blue terminal-blue)
     (ansi-color-magenta terminal-magenta)
     (ansi-color-cyan terminal-cyan)
     (ansi-color-white terminal-white)
     (vterm-color-default terminal-default)
     (vterm-color-black terminal-black)
     (vterm-color-red terminal-red)
     (vterm-color-green terminal-green)
     (vterm-color-yellow terminal-yellow)
     (vterm-color-blue terminal-blue)
     (vterm-color-magenta terminal-magenta)
     (vterm-color-cyan terminal-cyan)
     (vterm-color-white terminal-white)
     (vterm-color-bright-black terminal-bright-black)
     (vterm-color-bright-red terminal-bright-red)
     (vterm-color-bright-green terminal-bright-green)
     (vterm-color-bright-yellow terminal-bright-yellow)
     (vterm-color-bright-blue terminal-bright-blue)
     (vterm-color-bright-magenta terminal-bright-magenta)
     (vterm-color-bright-cyan terminal-bright-cyan)
     (vterm-color-bright-white terminal-bright-white)
     (vterm-color-inverse-video inverse)
     (vterm-color-underline link)
     (eat-shell-prompt-annotation-failure error)
     (eat-shell-prompt-annotation-running warning)
     (eat-shell-prompt-annotation-success success)
     (eat-term-bold bold)
     (eat-term-faint dim)
     (eat-term-italic italic)
     (eat-term-underline link)
     (eat-term-reverse-video inverse)
     (eat-term-blink default-plain)
     (eat-term-color-0 terminal-black)
     (eat-term-color-1 terminal-red)
     (eat-term-color-2 terminal-green)
     (eat-term-color-3 terminal-yellow)
     (eat-term-color-4 terminal-blue)
     (eat-term-color-5 terminal-magenta)
     (eat-term-color-6 terminal-cyan)
     (eat-term-color-7 terminal-white)
     (eat-term-color-8 terminal-bright-black)
     (eat-term-color-9 terminal-bright-red)
     (eat-term-color-10 terminal-bright-green)
     (eat-term-color-11 terminal-bright-yellow)
     (eat-term-color-12 terminal-bright-blue)
     (eat-term-color-13 terminal-bright-magenta)
     (eat-term-color-14 terminal-bright-cyan)
     (eat-term-color-15 terminal-bright-white)
     (calendar-today calendar-today)
     (calendar-weekday-header calendar-header)
     (calendar-weekend-header calendar-weekend)
     (calendar-month-header calendar-header)
     (diary calendar-today)
     (holiday calendar-holiday)
     (bv-calendar-header calendar-header)
     (bv-calendar-today calendar-today)
     (bv-calendar-current calendar-current)
     (bv-calendar-weekend calendar-weekend)
     (bv-calendar-holiday calendar-holiday)
     (elfeed-search-title-face default-plain)
     (elfeed-search-unread-title-face strong)
     (elfeed-search-feed-face heading-4)
     (elfeed-search-tag-face keybind)
     (elfeed-search-date-face dim)
     (elfeed-search-filter-face prompt)
     (elfeed-search-last-update-face dim)
     (elfeed-search-unread-count-face salient)
     (elfeed-log-date-face dim)
     (elfeed-log-debug-level-face dim)
     (elfeed-log-error-level-face error)
     (elfeed-log-info-level-face info)
     (elfeed-log-warn-level-face warning)
     (elfeed-score-date-face dim)
     (elfeed-score-debug-level-face dim)
     (elfeed-score-error-level-face error)
     (elfeed-score-info-level-face info)
     (elfeed-score-warn-level-face warning)
     (citar completion-annotation)
     (citar-highlight strong)
     (citar-isbn warning)
     (citar-org-highlight link)
     (citar-org-style-preview completion-annotation)
     (citar-note-highlight info)
     (citar-title strong)
     (citar-year dim)
     (citar-author syntax-function)
     (citar-journal syntax-string)
     (citar-tags keybind)
     (ebdb-field-name syntax-property)
     (ebdb-field-value default-plain)
     (message-cited-text-1 syntax-doc)
     (message-cited-text-2 syntax-comment)
     (message-cited-text-3 dim)
     (message-cited-text-4 dim)
     (message-header-cc dim)
     (message-header-name syntax-property)
     (message-header-newsgroups link)
     (message-header-other dim)
     (message-header-subject heading-4)
     (message-header-to link)
     (message-header-xheader dim)
     (message-mml syntax-keyword)
     (message-separator border)
     (mu4e-header-highlight-face completion-current)
     (mu4e-header-key-face syntax-property)
     (mu4e-header-title-face heading-4)
     (mu4e-header-marks-face keybind)
     (mu4e-header-value-face default-plain)
     (mu4e-contact-face link)
     (mu4e-draft-face warning)
     (mu4e-flagged-face warning)
     (mu4e-forwarded-face info)
     (mu4e-header-face default-plain)
     (mu4e-replied-face success)
     (mu4e-system-face dim)
     (mu4e-trashed-face error)
     (mu4e-unread-face strong)
     (mu4e-url-number-face keybind)
     (mm-uu-extract link)
     (gnus-button link)
     (gnus-emphasis-bold bold)
     (gnus-emphasis-bold-italic bold :slant italic)
     (gnus-emphasis-highlight-words match)
     (gnus-emphasis-italic italic)
     (gnus-emphasis-strikethru dim :strike-through t)
     (gnus-emphasis-underline link)
     (gnus-emphasis-underline-bold link :weight bold)
     (gnus-emphasis-underline-bold-italic link :weight bold :slant italic)
     (gnus-emphasis-underline-italic link :slant italic)
     (gnus-group-mail-1 heading-3)
     (gnus-group-mail-1-empty dim)
     (gnus-group-mail-2 heading-4)
     (gnus-group-mail-2-empty dim)
     (gnus-group-mail-3 salient)
     (gnus-group-mail-3-empty dim)
     (gnus-group-mail-low dim)
     (gnus-group-mail-low-empty faint)
     (gnus-group-news-1 heading-3)
     (gnus-group-news-1-empty dim)
     (gnus-group-news-2 heading-4)
     (gnus-group-news-2-empty dim)
     (gnus-group-news-3 salient)
     (gnus-group-news-3-empty dim)
     (gnus-group-news-4 info)
     (gnus-group-news-4-empty dim)
     (gnus-group-news-5 success)
     (gnus-group-news-5-empty dim)
     (gnus-group-news-6 warning)
     (gnus-group-news-6-empty dim)
     (gnus-group-news-low dim)
     (gnus-group-news-low-empty faint)
     (gnus-header heading-4)
     (gnus-header-content default-plain)
     (gnus-header-from link)
     (gnus-header-name syntax-property)
     (gnus-header-newsgroups link-muted)
     (gnus-header-subject heading-4)
     (gnus-signature dim)
     (gnus-splash heading-2)
     (gnus-summary-cancelled dim :strike-through t)
     (gnus-summary-high-ancient dim)
     (gnus-summary-high-read default-plain)
     (gnus-summary-high-ticked warning)
     (gnus-summary-high-undownloaded dim)
     (gnus-summary-high-unread strong)
     (gnus-summary-low-ancient faint)
     (gnus-summary-low-read dim)
     (gnus-summary-low-ticked warning)
     (gnus-summary-low-undownloaded faint)
     (gnus-summary-low-unread salient)
     (gnus-summary-normal-ancient dim)
     (gnus-summary-normal-read default-plain)
     (gnus-summary-normal-ticked warning)
     (gnus-summary-normal-undownloaded dim)
     (gnus-summary-normal-unread strong)
     (gnus-summary-selected completion-current)
     (font-latex-bold-face bold)
     (font-latex-italic-face italic)
     (font-latex-math-face syntax-string)
     (font-latex-script-char-face syntax-escape)
     (font-latex-sectioning-0-face heading-1)
     (font-latex-sectioning-1-face heading-2)
     (font-latex-sectioning-2-face heading-3)
     (font-latex-sectioning-3-face heading-4)
     (font-latex-sectioning-4-face heading-5)
     (font-latex-sectioning-5-face heading-6)
     (font-latex-sedate-face syntax-keyword)
     (font-latex-slide-title-face heading-2)
     (font-latex-string-face syntax-string)
     (font-latex-subscript-face default-plain :height 0.85)
     (font-latex-superscript-face default-plain :height 0.85)
     (font-latex-verbatim-face prose-code)
     (font-latex-warning-face warning)
     (subscript default-plain :height 0.85)
     (superscript default-plain :height 0.85)
     (TeX-error-description-error error)
     (TeX-error-description-help info)
     (TeX-error-description-tex-said warning)
     (TeX-error-description-warning warning)
     (tex-math syntax-string)
     (tex-verbatim prose-code)
     (preview-face prose-block)
     (preview-reference-face link)
     (preview-gs-face dim)
     (rainbow-delimiters-depth-1-face syntax-bracket)
     (rainbow-delimiters-depth-2-face syntax-keyword)
     (rainbow-delimiters-depth-3-face syntax-function)
     (rainbow-delimiters-depth-4-face syntax-string)
     (rainbow-delimiters-depth-5-face syntax-type)
     (rainbow-delimiters-depth-6-face syntax-constant)
     (rainbow-delimiters-depth-7-face syntax-builtin)
     (rainbow-delimiters-depth-8-face syntax-property)
     (rainbow-delimiters-depth-9-face syntax-preprocessor)
     (rainbow-delimiters-base-face syntax-bracket)
     (rainbow-delimiters-base-error-face error)
     (rainbow-delimiters-mismatched-face critical-block)
     (rainbow-delimiters-unmatched-face critical-block)
     (smartparens-overlay-face highlight)
     (smartparens-overlay-opening-pair-face match)
     (smartparens-overlay-closing-pair-face match)
     (smartparens-overlay-open-pair-face match)
     (sp-pair-overlay-face highlight)
     (sp-show-pair-match-face paren)
     (sp-show-pair-mismatch-face critical-block)
     (paren-face syntax-delimiter)
     (highlight-parentheses-highlight paren)
     (highlight-parentheses-background highlight)
     (nerd-icons-blue info)
     (nerd-icons-blue-alt info)
     (nerd-icons-cyan info)
     (nerd-icons-cyan-alt info)
     (nerd-icons-dblue salient)
     (nerd-icons-dcyan salient)
     (nerd-icons-dgreen success)
     (nerd-icons-dmaroon warning)
     (nerd-icons-dorange warning)
     (nerd-icons-dpink special)
     (nerd-icons-dpurple special)
     (nerd-icons-dred error)
     (nerd-icons-dsilver dim)
     (nerd-icons-dyellow warning)
     (nerd-icons-green success)
     (nerd-icons-green-alt success)
     (nerd-icons-lblue info)
     (nerd-icons-lcyan info)
     (nerd-icons-lgreen success)
     (nerd-icons-lmaroon warning)
     (nerd-icons-lorange warning)
     (nerd-icons-lpink special)
     (nerd-icons-lpurple special)
     (nerd-icons-lred error)
     (nerd-icons-lsilver dim)
     (nerd-icons-lyellow warning)
     (nerd-icons-maroon warning)
     (nerd-icons-orange warning)
     (nerd-icons-pink special)
     (nerd-icons-purple special)
     (nerd-icons-purple-alt special)
     (nerd-icons-red error)
     (nerd-icons-red-alt error)
     (nerd-icons-silver dim)
     (nerd-icons-yellow warning)
     (nerd-icons-yellow-alt warning)
     (dashboard-banner-logo-title heading-2)
     (dashboard-heading heading-4)
     (dashboard-items-face default-plain)
     (dashboard-no-items-face dim)
     (dashboard-navigator heading-4)
     (dashboard-text-banner heading-1)
     (dashboard-footer dim)
     (dashboard-footer-icon salient)
     (doom-dashboard-banner heading-1)
     (doom-dashboard-footer dim)
     (doom-dashboard-footer-icon salient)
     (doom-dashboard-loaded success)
     (doom-dashboard-menu-desc default-plain)
     (doom-dashboard-menu-title heading-4)
     (doom-dashboard-shortmenu keybind)
     (doom-dashboard-shortmenu-selected completion-current)
     (doom-dashboard-widget-title heading-4)
     (doom-dashboard-widget-footer dim)
     (doom-dashboard-widget-button button)
     (solaire-default-face default-plain)
     (solaire-hl-line-face hl-line)
     (solaire-line-number-face line-number)
     (solaire-mode-line-face mode-line-active)
     (solaire-mode-line-inactive-face mode-line-inactive)
     (solaire-org-hide-face faint)
     (solaire-region-face region)
     (bv-face-default default-plain)
     (bv-face-muted muted)
     (bv-face-dim dim)
     (bv-face-faint faint)
     (bv-face-salient salient)
     (bv-face-strong strong)
     (bv-face-critical critical)
     (bv-face-success success)
     (bv-face-warning warning)
     (bv-face-error error)
     (bv-face-info info)
     (bv-face-link link)
     (bv-face-prompt prompt)
     (bv-face-keybind keybind)
     (bv-face-match match)
     (bv-face-highlight highlight)
     (bv-face-secondary secondary)
     (bv-face-selection selection)
     (bv-icon-default default-plain)
     (bv-icon-muted dim)
     (bv-icon-file default-plain)
     (bv-icon-directory heading-4)
     (bv-icon-note default-plain)
     (bv-icon-code syntax-function)
     (bv-icon-science info)
     (bv-icon-idea special)
     (bv-icon-proof success)
     (bv-icon-review info)
     (bv-icon-index dim)
     (bv-icon-system salient)
     (bv-icon-warning warning)
     (bv-icon-success success)
     (bv-icon-special special)
     (bv-icon-info info)
     (bv-icon-salient salient)
     (bv-diagnostic-error diagnostic-error)
     (bv-diagnostic-warning diagnostic-warning)
     (bv-diagnostic-info diagnostic-info)
     (bv-diagnostic-note diagnostic-note)
     (bv-diff-added diff-added)
     (bv-diff-removed diff-removed)
     (bv-diff-changed diff-changed)
     (bv-diff-added-refine diff-added-refine)
     (bv-diff-removed-refine diff-removed-refine)
     (bv-diff-changed-refine diff-changed-refine)
     (bv-ui-header-default header-default)
     (bv-ui-header-muted header-muted)
     (bv-ui-header-strong header-strong)
     (bv-ui-header-salient header-salient)
     (bv-ui-header-info header-info)
     (bv-ui-header-warning header-warning)
     (bv-ui-header-error header-error)
     (bv-ui-header-popout header-popout)
     (bv-ui-header-critical header-critical)
     (bv-ui-header-inactive-default header-inactive-default)
     (bv-ui-header-inactive-muted header-inactive-muted)
     (bv-ui-header-inactive-strong header-inactive-strong)
     (bv-ui-header-inactive-salient header-inactive-salient)
     (bv-ui-header-inactive-info header-inactive-info)
     (bv-ui-header-inactive-warning header-inactive-warning)
     (bv-ui-header-inactive-error header-inactive-error)
     (bv-ui-header-inactive-popout header-inactive-popout)
     (bv-ui-header-inactive-critical header-inactive-critical)
     (abbrev-table-name heading-4)
     (ansi-color-bold bold)
     (ansi-color-faint dim)
     (ansi-color-fast-blink default-plain)
     (ansi-color-slow-blink default-plain)
     (ansi-color-italic italic)
     (ansi-color-inverse inverse)
     (ansi-color-underline link)
     (ansi-color-bright-black terminal-bright-black)
     (ansi-color-bright-red terminal-bright-red)
     (ansi-color-bright-green terminal-bright-green)
     (ansi-color-bright-yellow terminal-bright-yellow)
     (ansi-color-bright-blue terminal-bright-blue)
     (ansi-color-bright-magenta terminal-bright-magenta)
     (ansi-color-bright-cyan terminal-bright-cyan)
     (ansi-color-bright-white terminal-bright-white)
     (term-bold bold)
     (term-faint dim)
     (term-fast-blink default-plain)
     (term-slow-blink default-plain)
     (term-italic italic)
     (term-underline link)
     (term-color-bright-black terminal-bright-black)
     (term-color-bright-red terminal-bright-red)
     (term-color-bright-green terminal-bright-green)
     (term-color-bright-yellow terminal-bright-yellow)
     (term-color-bright-blue terminal-bright-blue)
     (term-color-bright-magenta terminal-bright-magenta)
     (term-color-bright-cyan terminal-bright-cyan)
     (term-color-bright-white terminal-bright-white)
     (eat-term-fast-blink default-plain)
     (eat-term-slow-blink default-plain)
     (eat-term-font-0 terminal-default)
     (eat-term-font-1 terminal-default)
     (eat-term-font-2 terminal-default)
     (eat-term-font-3 terminal-default)
     (eat-term-font-4 terminal-default)
     (eat-term-font-5 terminal-default)
     (eat-term-font-6 terminal-default)
     (eat-term-font-7 terminal-default)
     (eat-term-font-8 terminal-default)
     (eat-term-font-9 terminal-default)
     (completions-group-title heading-4)
     (completions-group-separator border)
     (consult-async-option dim)
     (consult-grep-context dim)
     (consult-help dim)
     (consult-key keybind)
     (consult-line-number line-number-current)
     (consult-narrow-indicator keybind)
     (consult-preview-insertion search-current)
     (consult-preview-line match)
     (dape-breakpoint-until-face warning)
     (dape-exception-description-face error)
     (dape-header-line-active-face header-strong)
     (dape-header-line-hover-face header-salient)
     (dape-header-line-inactive-face header-muted)
     (dape-hits-face match)
     (dape-inlay-hint-face dim)
     (dape-inlay-hint-highlight-face match)
     (dape-minibuffer-hint-separator-face border)
     (dape-source-line-face hl-line)
     (breakpoint-enabled error)
     (breakpoint-disabled dim)
     (diff-changed-unspecified diff-changed)
     (diff-error error)
     (diff-nonexistent diff-removed)
     (dired-set-id warning)
     (dired-special salient)
     (display-time-date-and-time mode-line-accent)
     (eglot-code-action-indicator-face warning)
     (eglot-parameter-hint-face dim)
     (eglot-type-hint-face dim)
     (eglot-semantic-abstract syntax-type)
     (eglot-semantic-async syntax-keyword)
     (eglot-semantic-class syntax-type)
     (eglot-semantic-comment syntax-comment)
     (eglot-semantic-declaration syntax-keyword)
     (eglot-semantic-decorator syntax-property)
     (eglot-semantic-defaultLibrary syntax-builtin)
     (eglot-semantic-definition syntax-function)
     (eglot-semantic-deprecated dim)
     (eglot-semantic-documentation syntax-doc)
     (eglot-semantic-enum syntax-type)
     (eglot-semantic-enumMember syntax-constant)
     (eglot-semantic-event syntax-function)
     (eglot-semantic-function syntax-function)
     (eglot-semantic-interface syntax-type)
     (eglot-semantic-keyword syntax-keyword)
     (eglot-semantic-macro syntax-preprocessor)
     (eglot-semantic-method syntax-function)
     (eglot-semantic-modification warning)
     (eglot-semantic-modifier syntax-keyword)
     (eglot-semantic-namespace syntax-builtin)
     (eglot-semantic-number syntax-number)
     (eglot-semantic-operator syntax-operator)
     (eglot-semantic-parameter syntax-variable)
     (eglot-semantic-property syntax-property)
     (eglot-semantic-readonly syntax-constant)
     (eglot-semantic-regexp syntax-regexp)
     (eglot-semantic-static syntax-keyword)
     (eglot-semantic-string syntax-string)
     (eglot-semantic-struct syntax-type)
     (eglot-semantic-type syntax-type)
     (eglot-semantic-typeParameter syntax-type)
     (eglot-semantic-variable syntax-variable)
     (elisp-shorthand-font-lock-face syntax-property)
     (embark-collect-candidate default-plain)
     (embark-keybinding-repeat keybind)
     (embark-keymap heading-4)
     (embark-selected completion-current)
     (embark-verbose-indicator-documentation prose-metadata)
     (embark-verbose-indicator-shadowed dim)
     (embark-verbose-indicator-title heading-4)
     (envrc-mode-line-error-face error)
     (envrc-mode-line-none-face dim)
     (envrc-mode-line-on-face success)
     (epa-field-body default-plain)
     (epa-field-name syntax-property)
     (epa-mark warning)
     (epa-string syntax-string)
     (epa-validity-disabled dim)
     (epa-validity-low error)
     (epa-validity-medium warning)
     (epa-validity-high success)
     (ert-test-result-expected success)
     (ert-test-result-unexpected error)
     (file-name-shadow dim)
     (fill-column-indicator border-subtle)
     (flymake-eol-information-face diagnostic-info)
     (flymake-error-echo diagnostic-error)
     (flymake-error-echo-at-eol diagnostic-error)
     (flymake-error-fringe error)
     (flymake-note-echo diagnostic-note)
     (flymake-note-echo-at-eol diagnostic-note)
     (flymake-note-fringe info)
     (flymake-warning-echo diagnostic-warning)
     (flymake-warning-echo-at-eol diagnostic-warning)
     (flymake-warning-fringe warning)
     (font-lock-function-call-face syntax-function)
     (font-lock-misc-punctuation-face syntax-delimiter)
     (font-lock-punctuation-face syntax-delimiter)
     (font-lock-regexp-face syntax-regexp)
     (grep-heading heading-4)
     (gud-highlight-current-line-face hl-line)
     (hexl-address-region region)
     (hexl-ascii-region region)
     (ibuffer-locked-buffer error)
     (icon default-plain)
     (icon-button button)
     (ido-indicator warning)
     (keycast-command mode-line-accent)
     (keycast-key keybind)
     (kmacro-menu-flagged warning)
     (kmacro-menu-mark success)
     (kmacro-menu-marked completion-current)
     (line-number-major-tick line-number-current)
     (line-number-minor-tick line-number)
     (menu default-plain)
     (mm-command-output prose-block)
     (mouse cursor)
     (mouse-drag-and-drop-region region)
     (nobreak-hyphen escape)
     (olivetti-fringe fringe)
     (persp-selected-face mode-line-accent)
     (read-multiple-choice-face keybind)
     (scroll-bar border)
     (separator-line border)
     (show-paren-match-expression paren)
     (so-long-mode-line-active mode-line-accent)
     (so-long-mode-line-inactive mode-line-inactive)
     (tabulated-list-fake-header header-strong)
     (table-cell border-subtle)
     (tempel-default match)
     (tempel-field region)
     (tempel-form completion-current)
     (tool-bar tab-bar)
     (transient-active-infix completion-current)
     (transient-delimiter border)
     (transient-inactive-argument dim)
     (transient-inapt-argument dim)
     (transient-inapt-suffix dim)
     (transient-key-exit keybind)
     (transient-key-noop dim)
     (transient-key-recurse keybind)
     (transient-key-return keybind)
     (transient-key-stack keybind)
     (transient-key-stay keybind)
     (tty-menu-disabled-face dim)
     (tty-menu-enabled-face default-plain)
     (tty-menu-selected-face completion-current)
     (vundo-branch-stem dim)
     (vundo-default default-plain)
     (vundo-highlight completion-current)
     (vundo-last-saved success)
     (vundo-node salient)
     (vundo-saved success)
     (vundo-stem dim)
     (which-key-docstring-face prose-metadata)
     (which-key-highlighted-command-face completion-match)
     (widget-unselected dim)
     (world-clock-label heading-4)
     (battery-load-critical error)
     (battery-load-low warning)
     (bv-layout-fallback dim)
     (apropos-variable-button syntax-variable)
     (avy-goto-char-timer-face mode-line-accent)
     (aw-background-face faint)
     (aw-key-face mode-line-accent)
     (aw-leading-char-face mode-line-accent)
     (aw-minibuffer-leading-char-face keybind)
     (aw-mode-line-face mode-line-accent)
     (blink-matching-paren-offscreen warning)
     (browse-url-button link)
     (c-annotation-face syntax-preprocessor)
     (c-nonbreakable-space-face warning-subtle)
     (edebug-disabled-breakpoint dim)
     (edebug-enabled-breakpoint error)
     (edit-indirect-edited-region region)
     (llama-deleted-argument dim :strike-through t)
     (llama-llama-macro syntax-keyword)
     (llama-mandatory-argument syntax-variable)
     (llama-optional-argument dim)
     (which-func mode-line-accent)
     (citar-selection completion-current)
     (combobulate-active-indicator-face success)
     (combobulate-dimmed-indicator-face dim)
     (combobulate-error-indicator-face error)
     (combobulate-highlight-context-face match)
     (combobulate-query-highlight-fiery-flames-face error-subtle)
     (combobulate-query-highlight-gleaming-gold-face warning-subtle)
     (combobulate-query-highlight-majestic-mercury-face info-subtle)
     (combobulate-query-highlight-mysterious-mauve-face error-subtle)
     (combobulate-query-highlight-radiant-rind-face warning-subtle)
     (combobulate-query-highlight-regal-ripples-face info-subtle)
     (combobulate-query-highlight-serene-shade-face success-subtle)
     (combobulate-query-highlight-silver-shadows-face highlight)
     (combobulate-query-highlight-underline-blue-face diagnostic-info)
     (combobulate-query-highlight-underline-red-face diagnostic-error)
     (combobulate-query-highlight-vibrant-veggie-face success-subtle)
     (combobulate-query-query-anonymous-face syntax-variable)
     (combobulate-query-query-builtin-face syntax-builtin)
     (combobulate-query-query-constant-face syntax-constant)
     (combobulate-query-query-doc-markup-face syntax-doc)
     (combobulate-query-query-keyword-face syntax-keyword)
     (combobulate-query-query-predicate-builtin-face syntax-builtin)
     (combobulate-query-query-string-face syntax-string)
     (combobulate-refactor-choice-face keybind)
     (combobulate-refactor-cursor-face cursor)
     (combobulate-refactor-disabled-field-face dim)
     (combobulate-refactor-field-face region)
     (combobulate-refactor-highlight-face match)
     (combobulate-refactor-inactive-choice-face dim)
     (combobulate-refactor-inactive-field-face dim)
     (combobulate-refactor-label-face syntax-property)
     (combobulate-tree-branch-face dim)
     (combobulate-tree-highlighted-node-face completion-current)
     (combobulate-tree-normal-node-face default-plain)
     (combobulate-tree-pulse-node-face match)
     (confusingly-reordered warning)
     (edmacro-label heading-4)
     (ffap match)
     (sh-escaped-newline syntax-escape)
     (sh-heredoc syntax-string)
     (sh-quoted-exec syntax-function)
     (sgml-namespace syntax-builtin)
     (shell-highlight-undef-alias-face warning)
     (shell-highlight-undef-defined-face success)
     (shell-highlight-undef-undefined-face error)
     (treesit-explorer-anonymous-node dim)
     (treesit-explorer-field-name syntax-property)
     (biblio-detail-header-face heading-4)
     (biblio-highlight-extend-face match)
     (biblio-results-header-face heading-4)
     (elfeed-score-scoring-explain-text-face default-plain)
     (info-command-ref-item keybind)
     (info-constant-ref-item syntax-constant)
     (info-custom-delimited prose-code)
     (info-double-quoted-name syntax-string)
     (info-emphasis italic)
     (info-file heading-4)
     (info-fixed-pitch prose-code)
     (info-function-ref-item syntax-function)
     (info-glossary-word salient)
     (info-homoglyph escape)
     (info-indented-text prose-block)
     (info-isolated-backquote prose-code)
     (info-isolated-quote prose-code)
     (info-macro-ref-item syntax-preprocessor)
     (info-menu link)
     (info-quoted-name syntax-string)
     (info-reference-item link)
     (info-special-form-ref-item syntax-keyword)
     (info-string syntax-string)
     (info-syntax-class-item syntax-type)
     (info-user-option-ref-item syntax-variable)
     (info-variable-ref-item syntax-variable)
     (message-signature-separator border)
     (nerd-icons-completion-dir-face default-plain)
     (nerd-icons-dired-dir-face heading-4)
     (nerd-icons-ibuffer-dir-face heading-4)
     (nerd-icons-ibuffer-file-face default-plain)
     (nerd-icons-ibuffer-icon-face salient)
     (nerd-icons-ibuffer-mode-face syntax-keyword)
     (nerd-icons-ibuffer-size-face dim)
     (org-agenda-calendar-daterange info)
     (org-agenda-date-weekend-today heading-3)
     (org-agenda-diary default-plain)
     (org-agenda-structure-filter keybind)
     (org-agenda-structure-secondary dim)
     (org-clock-overlay warning-subtle)
     (org-column completion)
     (org-column-title header-strong)
     (org-date-selected completion-current)
     (org-default default-plain)
     (org-dispatcher-highlight completion-current)
     (org-ellipsis dim)
     (org-headline-todo prose-todo)
     (org-hide faint)
     (org-imminent-deadline error)
     (org-inline-src-block prose-block)
     (org-latex-and-related syntax-string)
     (org-macro syntax-preprocessor)
     (org-mode-line-clock mode-line-accent)
     (org-mode-line-clock-overrun error)
     (org-quote prose-block)
     (org-ref-acronym-face syntax-constant)
     (org-ref-bad-cite-key-face error)
     (org-ref-cite-&-face link)
     (org-ref-cite-face link)
     (org-ref-cite-global-prefix/suffix-face prose-metadata)
     (org-ref-cite-invalid-local-prefix/suffix-face error)
     (org-ref-cite-local-prefix/suffix-face prose-metadata)
     (org-ref-glossary-face link)
     (org-ref-label-face syntax-property)
     (org-ref-ref-face link)
     (org-slipbox-dailies-calendar-note match)
     (org-table-header header-strong)
     (org-table-row prose-table)
     (org-tag-group dim)
     (org-target match)
     (org-upcoming-distant-deadline warning)
     (org-verse prose-block)
     (rst-adornment heading-4)
     (rst-block prose-block)
     (rst-comment syntax-comment)
     (rst-definition syntax-property)
     (rst-directive syntax-keyword)
     (rst-emphasis1 italic)
     (rst-emphasis2 bold)
     (rst-external link)
     (rst-literal prose-code)
     (rst-reference link)
     (rst-transition border)
     (shr-mark match)
     (shr-sup default-plain :height 0.85)
     (sly-action-face keybind)
     (sly-apropos-label syntax-property)
     (sly-apropos-symbol syntax-variable)
     (sly-db-catch-tag-face warning)
     (sly-db-condition-face error)
     (sly-db-frame-label-face dim)
     (sly-db-frame-line-face default-plain)
     (sly-db-local-name-face syntax-variable)
     (sly-db-non-restartable-frame-line-face dim)
     (sly-db-restart-face success)
     (sly-db-restart-number-face keybind)
     (sly-db-restartable-frame-line-face success)
     (sly-db-section-face heading-4)
     (sly-db-topline-face header-strong)
     (sly-error-face diagnostic-error)
     (sly-mode-line mode-line-accent)
     (sly-note-face diagnostic-note)
     (sly-part-button-face button)
     (sly-style-warning-face diagnostic-warning)
     (sly-warning-face diagnostic-warning)
     (lispy-command-name-face keybind)
     (lispy-cursor-face cursor)
     (lispy-face-hint dim)
     (lispy-face-key-nosel keybind)
     (lispy-face-key-sel mode-line-accent)
     (lispy-face-opt-nosel dim)
     (lispy-face-opt-sel warning)
     (lispy-face-req-nosel warning)
     (lispy-face-req-sel critical)
     (lispy-face-rst-nosel info)
     (lispy-face-rst-sel success)
     (lispy-test-face success)
     (sp-show-pair-enclosing paren)
     (sp-show-pair-match-content-face match)
     (sp-wrap-overlay-closing-pair paren)
     (sp-wrap-overlay-face highlight)
     (sp-wrap-overlay-opening-pair paren)
     (sp-wrap-tag-overlay-face match)
     (tab-bar-tab-group-current tab-current)
     (tab-bar-tab-group-inactive tab-other)
     (tab-bar-tab-ungrouped tab-other)
     (vc-ignored-state dim))
   (bv-themes-adapters--indexed
    "ansi-color"
    '(terminal-black terminal-red terminal-green terminal-yellow
      terminal-blue terminal-magenta terminal-cyan terminal-white))
   (bv-themes-adapters--indexed
    "ansi-color"
    '(terminal-bright-black terminal-bright-red terminal-bright-green
      terminal-bright-yellow terminal-bright-blue terminal-bright-magenta
      terminal-bright-cyan terminal-bright-white)
    8)
   (bv-themes-adapters--indexed
    "vterm-color"
    '(terminal-black terminal-red terminal-green terminal-yellow
      terminal-blue terminal-magenta terminal-cyan terminal-white))
   (bv-themes-adapters--indexed
    "vterm-color"
    '(terminal-bright-black terminal-bright-red terminal-bright-green
      terminal-bright-yellow terminal-bright-blue terminal-bright-magenta
      terminal-bright-cyan terminal-bright-white)
    8)
   (list (list (intern "llama-##-macro") 'syntax-keyword))
   (bv-themes-adapters--terminal-range "eat-term-color" 16 255))
  "Concrete face-to-role adapter specifications.")

(defun bv-themes-adapters--rule-match-p (face rule)
  "Return non-nil if FACE matches package RULE."
  (let ((name (symbol-name face))
        (faces (plist-get rule :faces))
        (prefixes (plist-get rule :prefixes)))
    (or (memq face faces)
        (cl-some (lambda (prefix)
                   (string-prefix-p prefix name))
                 prefixes))))

(defun bv-themes-adapters-package-for-face (face)
  "Return the package owner for FACE."
  (catch 'package
    (dolist (entry bv-themes-adapter-package-rules)
      (when (bv-themes-adapters--rule-match-p face (cdr entry))
        (throw 'package (car entry))))
    nil))

(defun bv-themes-adapters-record (entry)
  "Return a metadata record for adapter ENTRY."
  (let* ((face (car entry))
         (role (cadr entry))
         (overrides (cddr entry)))
    (list :face face
          :role role
          :package (bv-themes-adapters-package-for-face face)
          :purpose role
          :overrides overrides
          :critical (memq role
                          '(critical critical-block error error-subtle
                            warning warning-subtle success success-subtle
                            info info-subtle diagnostic-error
                            diagnostic-warning diagnostic-info
                            diagnostic-note diff-added diff-removed
                            diff-changed terminal-default terminal-black
                            terminal-red terminal-green terminal-yellow
                            terminal-blue terminal-magenta terminal-cyan
                            terminal-white terminal-bright-black
                            terminal-bright-red terminal-bright-green
                            terminal-bright-yellow terminal-bright-blue
                            terminal-bright-magenta terminal-bright-cyan
                            terminal-bright-white)))))

(defun bv-themes-adapters-records ()
  "Return all face adapter metadata records."
  (mapcar #'bv-themes-adapters-record bv-themes-adapter-specs))

(defun bv-themes-adapters-package-counts ()
  "Return adapter counts grouped by package."
  (let (counts)
    (dolist (record (bv-themes-adapters-records))
      (let ((package (or (plist-get record :package) 'unowned)))
        (setf (alist-get package counts)
              (1+ (or (alist-get package counts) 0)))))
    (sort counts (lambda (left right)
                   (string< (symbol-name (car left))
                            (symbol-name (car right)))))))

(provide 'bv-themes-adapters)
;;; bv-themes-adapters.el ends here
