;;; bv-dark-theme.el --- BV dark theme specification -*- lexical-binding: t -*-

;; Copyright (C) 2026 Ayan Das
;; Author: Ayan Das <bvits@riseup.net>

;;; Commentary:

;; Ink and Frost dark profile authored with perceptual anchors and semantic
;; role overrides.

;;; Code:

(require 'bv-themes)

(bv-themes-define-theme bv-dark
  (metadata
   :display-name "BV Dark"
   :summary "Sumi-ink dark profile with lacquer depth, warm paper text, and elemental pigment accents."
   :tags '(dark sumi ink lacquer indigo pigment paper prose code terminal)
   :family 'ink-and-frost
   :version 3)
  (variant dark
   :polarity -1
   :modes '(gui tty)
   :ambient 'night)
  (anchors
   (neutral
    (bg-main (oklch 0.1900 0.0140 260.0))
    (bg-dim (oklch 0.1650 0.0130 260.0))
    (fg-main (oklch 0.8900 0.0180 92.0)))
   (state
    (red (oklch 0.6720 0.1180 28.0))
    (orange (oklch 0.7000 0.0880 58.0))
    (yellow (oklch 0.8050 0.0980 100.0))
    (green (oklch 0.7150 0.0820 136.0)))
   (accent
    (teal (oklch 0.6800 0.0700 188.0))
    (cyan (oklch 0.6600 0.0780 222.0))
    (blue (oklch 0.6150 0.1150 263.0))
    (purple (oklch 0.6100 0.0950 306.0))
    (magenta (oklch 0.6300 0.0900 336.0))))
  (surfaces
   (bg-dim-dark :amount 0.035 :intent base-lift)
   (bg-alt :amount 0.082 :intent quiet-layer)
   (bg-alt-2 :amount 0.122 :intent raised-layer)
   (bg-active :amount 0.170 :intent active-row)
   (bg-hover :amount 0.132 :intent pointer-target)
   (bg-hover-secondary :amount 0.116 :intent secondary-target)
   (bg-region :amount 0.300 :intent selection)
   (bg-region-subtle :amount 0.180 :intent secondary-selection)
   (bg-hl-line :amount 0.058 :intent reading-line)
   (bg-header :amount 0.000 :intent structural-band)
   (bg-header-strong :amount 0.102 :intent prominent-band)
   (bg-completion-current :amount 0.300 :intent completion-focus)
   (bg-prose-block-contents :amount 0.050 :intent prose-block)
   (bg-markup-code :amount 0.070 :intent inline-code)
   (fg-muted :amount 0.700 :intent secondary-text)
   (fg-dim :amount 0.560 :intent tertiary-text)
   (fg-faint :amount 0.420 :intent disabled-text)
   (border :amount 0.242 :intent visible-boundary)
   (border-subtle :amount 0.158 :intent quiet-boundary)
   (border-strong :amount 0.405 :intent emphasized-boundary))
  (tones
   (faint :amount 0.775)
   (subtle :amount 0.198)
   (subtle-2 :amount 0.282)
   (strong-chroma-scale :amount 1.045))
  (ui
   (salient blue-strong)
   (special purple-strong)
   (special-mild purple-faint)
   (header fg-active)
   (header-muted fg-muted)
   (cursor blue-strong)
   (prompt orange-strong)
   (keybind blue-strong)
   (accent-0 blue)
   (accent-1 purple)
   (accent-2 green)
   (accent-3 orange))
  (syntax
   (comment (oklch 0.6120 0.0200 250.0))
   (doc teal)
   (string green-strong)
   (regexp purple-strong)
   (escape red-strong)
   (keyword purple)
   (builtin cyan)
   (function blue-strong)
   (variable fg-main)
   (constant yellow-strong)
   (number orange)
   (type teal-strong)
   (operator fg-main)
   (preprocessor orange-strong)
   (property fg-main)
   (bracket fg-main)
   (delimiter fg-muted))
  (prose
   (heading-1 blue-strong)
   (heading-2 fg-main)
   (heading-3 yellow-strong)
   (heading-4 teal-strong)
   (heading-5 green-strong)
   (heading-6 purple-strong)
   (heading-7 orange-strong)
   (heading-8 fg-muted)
   (link blue)
   (visited purple)
   (code cyan-strong)
   (verbatim orange-strong)
   (metadata fg-muted)
   (metadata-value fg-active)
   (table fg-main)
   (todo red)
   (done green))
  (states
   (success green)
   (success-strong green-strong)
   (warning yellow)
   (warning-strong yellow-strong)
   (error red)
   (error-strong red-strong)
   (info cyan)
   (info-strong cyan-strong)
   (critical red)
   (critical-bg (tone red subtle))
   (critical-fg red-strong))
  (search
   (background (mix yellow bg-main 0.200))
   (foreground fg-main)
   (current-background (mix orange bg-main 0.245))
   (current-foreground fg-main)
   (lazy-background (mix cyan bg-main 0.170))
   (match-background (mix green bg-main 0.190))
   (paren-background (mix blue bg-main 0.255))
   (paren-foreground fg-main))
  (diff
   (added-background (tone green subtle))
   (added-refine (tone green subtle-2))
   (added-foreground green-strong)
   (removed-background (tone red subtle))
   (removed-refine (tone red subtle-2))
   (removed-foreground red-strong)
   (changed-background (tone yellow subtle))
   (changed-refine (tone yellow subtle-2))
   (changed-foreground yellow-strong))
  (modeline
   (active-background (oklch 0.2740 0.0360 263.0))
   (active-foreground fg-active)
   (inactive-background (oklch 0.2160 0.0160 260.0))
   (inactive-foreground fg-dim)
   (active-border border)
   (inactive-border bg-dim)
   (accent-background blue)
   (accent-foreground bg-main)
   (critical-background red)
   (critical-foreground bg-main))
  (links
   (normal blue)
   (faint blue-faint)
   (visited purple))
  (terminal
   (black bg-alt)
   (red red)
   (green green)
   (yellow yellow)
   (blue blue)
   (magenta magenta)
   (cyan cyan)
   (white fg-active)
   (bright-black border)
   (bright-red red-strong)
   (bright-green green-strong)
   (bright-yellow yellow-strong)
   (bright-blue blue-strong)
   (bright-magenta magenta-strong)
   (bright-cyan cyan-strong)
   (bright-white fg-active))
  (tokens
   (bg-dim (oklch 0.1650 0.0130 260.0))
   (bg-alt (oklch 0.2320 0.0170 262.0))
   (bg-alt-2 (oklch 0.2680 0.0200 262.0))
   (bg-active (oklch 0.2960 0.0250 262.0))
   (bg-hover (oklch 0.2580 0.0210 262.0))
   (bg-hover-secondary (oklch 0.2820 0.0240 262.0))
   (bg-hl-line (oklch 0.2220 0.0160 262.0))
   (bg-region (mix blue bg-main 0.305))
   (bg-region-subtle (mix blue bg-main 0.205))
   (bg-selected bg-region)
   (bg-tab-bar bg-dim)
   (bg-tab-current bg-main)
   (bg-tab-other bg-alt)
   (bg-header bg-active)
   (bg-header-strong bg-active)
   (bg-tooltip bg-active)
   (bg-completion bg-alt)
   (bg-completion-current (mix blue bg-main 0.300))
   (bg-popup bg-alt)
   (bg-prose-block bg-alt)
   (bg-prose-block-contents bg-dim)
   (bg-markup-code bg-dim)
   (fg-muted (oklch 0.7520 0.0180 92.0))
   (fg-dim (oklch 0.6120 0.0160 250.0))
   (fg-faint (oklch 0.4800 0.0160 250.0))
   (fg-active (oklch 0.9260 0.0160 92.0))
   (fg-inverse bg-main)
   (fg-header-inverse bg-main)
   (border (oklch 0.3600 0.0220 262.0))
   (border-subtle bg-dim)
   (border-strong bg-active)
   (red-faint (oklch 0.5550 0.0600 28.0))
   (red-strong (oklch 0.7180 0.1450 28.0))
   (orange-faint (oklch 0.5480 0.0480 58.0))
   (orange-strong (oklch 0.7480 0.1050 58.0))
   (yellow-faint (oklch 0.6100 0.0480 100.0))
   (yellow-strong (oklch 0.8450 0.1180 100.0))
   (green-faint (oklch 0.5550 0.0480 136.0))
   (green-strong (oklch 0.7680 0.1000 136.0))
   (teal-faint (oklch 0.5300 0.0400 188.0))
   (teal-strong (oklch 0.7280 0.0860 188.0))
   (cyan-faint (oklch 0.5320 0.0440 222.0))
   (cyan-strong (oklch 0.7160 0.0960 222.0))
   (blue-faint (oklch 0.5300 0.0550 263.0))
   (blue-strong (oklch 0.6700 0.1320 263.0))
   (purple-faint (oklch 0.5280 0.0580 306.0))
   (purple-strong (oklch 0.6600 0.1120 306.0))
   (magenta-faint (oklch 0.5400 0.0550 336.0))
   (magenta-strong (oklch 0.6820 0.1080 336.0))
   (accent-0-subtle blue-subtle)
   (accent-1-subtle purple-subtle)
   (accent-2-subtle green-subtle)
   (accent-3-subtle orange-subtle)
   (accent-0-intense blue-strong)
   (accent-1-intense purple-strong)
   (accent-2-intense green-strong)
   (accent-3-intense orange-strong))
  (roles
   (variable-pitch-text :fg fg-main :bg bg-main
                        :family-var bv-themes-font-family-proportional
                        :height 1.0)
   (strong :fg fg-main :weight medium)
   (salient :fg fg-salient :weight medium)
   (special :fg fg-special :weight medium)
   (escape :fg syntax-escape :weight medium)
   (match :fg fg-main :bg bg-match :weight medium)
   (search :fg fg-search :bg bg-search :weight medium)
   (search-current :fg fg-search-current :bg bg-search-current
                   :weight medium)
   (paren :fg fg-paren :bg bg-paren :weight medium)
   (link :fg fg-link :underline nil)
   (link-visited :fg fg-link-visited :underline nil)
   (link-muted :fg fg-link-faint :underline nil)
   (prompt :fg prompt :weight medium)
   (keybind :fg keybind :weight medium)
   (success :fg success :weight medium)
   (warning :fg warning-strong :weight medium)
   (error :fg error-strong :weight medium)
   (info :fg info-strong :weight medium)
   (syntax-regexp :fg syntax-regexp :weight medium)
   (syntax-escape :fg syntax-escape :weight medium)
   (syntax-keyword :fg syntax-keyword :weight medium)
   (syntax-builtin :fg syntax-builtin)
   (syntax-function :fg syntax-function :weight medium)
   (syntax-constant :fg syntax-constant)
   (syntax-type :fg syntax-type)
   (syntax-preprocessor :fg syntax-preprocessor :weight medium)
   (line-number-current :fg fg-main :bg bg-hl-line)
   (header-default :fg fg-header :bg bg-header :extend t)
   (header-muted :fg fg-header-muted :bg bg-header :extend t)
   (header-strong :fg fg-header :bg bg-header :weight medium :extend t)
   (header-salient :fg fg-salient :bg bg-header
                   :weight medium :extend t)
   (header-popout :fg fg-header-inverse :bg modeline-bg-active
                  :weight medium :extend t)
   (mode-line-active :fg modeline-fg-active :bg modeline-bg-active)
   (mode-line-inactive :fg modeline-fg-inactive :bg modeline-bg-inactive)
   (mode-line-accent :fg modeline-fg-accent :bg modeline-bg-accent
                     :weight medium)
   (tab-current :fg fg-main :bg bg-tab-current :weight medium)
   (completion-current :fg fg-main :bg bg-completion-current
                       :weight medium :extend t)
   (completion-match :fg fg-salient :weight medium)
   (button :fg fg-link :bg bg-hover :underline nil :weight medium)
   (heading-1 :fg prose-heading-1 :weight medium :height 1.0)
   (heading-2 :fg prose-heading-2 :weight medium :height 1.0)
   (heading-3 :fg prose-heading-3 :weight medium :height 1.0)
   (heading-4 :fg prose-heading-4 :weight medium :height 1.0)
   (heading-5 :fg prose-heading-5 :height 1.0)
   (heading-6 :fg prose-heading-6 :height 1.0)
   (heading-7 :fg prose-heading-7 :height 1.0)
   (heading-8 :fg prose-heading-8 :height 1.0)
   (prose-title :fg blue-strong :weight bold :height 1.1
                :family-var bv-themes-font-family-proportional)
   (prose-subtitle :fg fg-muted :height 1.0
                   :family-var bv-themes-font-family-proportional)
   (prose-todo :fg prose-todo :weight medium)
   (prose-done :fg prose-done :weight medium)
   (diff-added-refine :fg fg-added :bg bg-added-refine :weight medium)
   (diff-removed-refine :fg fg-removed :bg bg-removed-refine
                        :weight medium)
   (diff-changed-refine :fg fg-changed :bg bg-changed-refine
                        :weight medium)
   (diff-header :fg fg-main :bg bg-alt :weight medium :extend t)
   (diff-file-header :fg fg-salient :bg bg-alt-2
                     :weight medium :extend t)
   (vc-added :fg fg-added :weight medium)
   (vc-removed :fg fg-removed :weight medium)
   (vc-changed :fg fg-changed :weight medium)
   (calendar-header :fg prose-heading-1 :weight medium)
   (calendar-today :fg blue-strong :weight medium)
   (calendar-current :fg fg-main :bg bg-region :weight medium)
   (bv-gallery-title :define t :fg prose-heading-1
                     :weight medium :height 1.0)
   (bv-gallery-summary :define t :fg fg-muted)
   (bv-gallery-swatch-label :define t :fg fg-dim)
   (bv-gallery-swatch-border :define t :fg border-subtle))
  (faces
   (bv-theme-gallery-title bv-gallery-title)
   (bv-theme-gallery-summary bv-gallery-summary)
   (bv-theme-gallery-swatch-label bv-gallery-swatch-label)
   (bv-theme-gallery-swatch-border bv-gallery-swatch-border))
  (gallery
   :swatches '(neutral state accent syntax prose terminal)
   :samples '(code diff org minibuffer modeline calendar feeds terminal)
   :background 'charcoal
   :density 'high)
  (policy
   :underlines nil
   :contrast-target 'aesthetic
   :terminal-colors 256
   :gamut 'srgb)
  (samples
   (code "async fn refresh_buffer")
   (prose "* Night reading queue")
   (diff "- stale adapter edge"))
  (notes
   "Dark now reads as sumi ink and lacquer: warm paper text, indigo-cobalt structure, bengara and moss accents, oxidized copper blues, and yuzu as a narrow edge."))

;;; bv-dark-theme.el ends here
