;;; bv-dark-theme.el --- BV dark theme specification -*- lexical-binding: t -*-

;; Copyright (C) 2026 Ayan Das
;; Author: Ayan Das <bvits@riseup.net>

;;; Commentary:

;; Ink and Frost dark profile authored with perceptual anchors and semantic
;; role overrides.

;;; Code:

(require 'bv-themes)

(bv-themes-define-theme bv-dark
  (metadata
   :display-name "BV Dark"
   :summary "Ink and Frost dark profile with charcoal surfaces, frost-blue structure, and warm paper accents."
   :tags '(dark charcoal ink frost prose code terminal)
   :family 'ink-and-frost
   :version 2)
  (variant dark
   :polarity -1
   :modes '(gui tty)
   :ambient 'night)
  (anchors
   (neutral
    (bg-main (oklch 0.2686 0.0097 268.3))
    (bg-dim (oklch 0.2478 0.0099 268.3))
    (fg-main (oklch 0.8296 0.0165 253.9)))
   (state
    (red (oklch 0.6709 0.1448 17.0))
    (orange (oklch 0.5871 0.0679 64.3))
    (yellow (oklch 0.7653 0.0764 86.6))
    (green (oklch 0.6179 0.0793 132.8)))
   (accent
    (teal (oklch 0.6259 0.0745 218.1))
    (cyan (oklch 0.6000 0.0694 214.7))
    (blue (oklch 0.6136 0.0907 244.3))
    (purple (oklch 0.5624 0.1140 318.3))
    (magenta (oklch 0.5598 0.1028 348.0))))
  (surfaces
   (bg-dim-dark :amount 0.035 :intent base-lift)
   (bg-alt :amount 0.074 :intent quiet-layer)
   (bg-alt-2 :amount 0.112 :intent raised-layer)
   (bg-active :amount 0.158 :intent active-row)
   (bg-hover :amount 0.128 :intent pointer-target)
   (bg-hover-secondary :amount 0.116 :intent secondary-target)
   (bg-region :amount 0.260 :intent selection)
   (bg-region-subtle :amount 0.180 :intent secondary-selection)
   (bg-hl-line :amount 0.050 :intent reading-line)
   (bg-header :amount 0.000 :intent structural-band)
   (bg-header-strong :amount 0.102 :intent prominent-band)
   (bg-completion-current :amount 0.235 :intent completion-focus)
   (bg-prose-block-contents :amount 0.050 :intent prose-block)
   (bg-markup-code :amount 0.070 :intent inline-code)
   (fg-muted :amount 0.700 :intent secondary-text)
   (fg-dim :amount 0.560 :intent tertiary-text)
   (fg-faint :amount 0.420 :intent disabled-text)
   (border :amount 0.242 :intent visible-boundary)
   (border-subtle :amount 0.158 :intent quiet-boundary)
   (border-strong :amount 0.405 :intent emphasized-boundary))
  (tones
   (faint :amount 0.775)
   (subtle :amount 0.198)
   (subtle-2 :amount 0.282)
   (strong-chroma-scale :amount 1.060))
  (ui
   (salient blue-strong)
   (special purple)
   (special-mild purple-faint)
   (header fg-active)
   (header-muted fg-muted)
   (cursor blue)
   (prompt orange-strong)
   (keybind blue)
   (accent-0 blue)
   (accent-1 purple)
   (accent-2 green)
   (accent-3 orange))
  (syntax
   (comment (oklch 0.6351 0.0165 260.7))
   (doc green)
   (string green-strong)
   (regexp purple-strong)
   (escape (oklch 0.7067 0.0902 342.3))
   (keyword purple)
   (builtin cyan)
   (function blue-strong)
   (variable red)
   (constant cyan)
   (number orange)
   (type orange)
   (operator fg-main)
   (preprocessor orange-strong)
   (property fg-main)
   (bracket fg-main)
   (delimiter fg-muted))
  (prose
   (heading-1 fg-main)
   (heading-2 yellow)
   (heading-3 fg-active)
   (heading-4 blue)
   (heading-5 green)
   (heading-6 purple)
   (heading-7 orange)
   (heading-8 fg-muted)
   (link blue)
   (visited purple)
   (code cyan-faint)
   (verbatim orange-faint)
   (metadata fg-muted)
   (metadata-value fg-active)
   (table fg-main)
   (todo red)
   (done green))
  (states
   (success green)
   (success-strong green-strong)
   (warning yellow)
   (warning-strong yellow-strong)
   (error red)
   (error-strong red-strong)
   (info cyan)
   (info-strong cyan-strong)
   (critical red)
   (critical-bg (tone red subtle))
   (critical-fg red-strong))
  (search
   (background (mix yellow bg-main 0.280))
   (foreground fg-main)
   (current-background (mix orange bg-main 0.340))
   (current-foreground fg-main)
   (lazy-background (mix cyan bg-main 0.220))
   (match-background (mix cyan bg-main 0.240))
   (paren-background (tone cyan subtle-2))
   (paren-foreground fg-main))
  (diff
   (added-background (tone green subtle))
   (added-refine (tone green subtle-2))
   (added-foreground green-strong)
   (removed-background (tone red subtle))
   (removed-refine (tone red subtle-2))
   (removed-foreground red-strong)
   (changed-background (tone yellow subtle))
   (changed-refine (tone yellow subtle-2))
   (changed-foreground yellow-strong))
  (modeline
   (active-background bg-active)
   (active-foreground fg-active)
   (inactive-background (oklch 0.2566 0.0116 270.9))
   (inactive-foreground fg-dim)
   (active-border border)
   (inactive-border bg-dim)
   (accent-background blue)
   (accent-foreground bg-main)
   (critical-background red)
   (critical-foreground bg-main))
  (links
   (normal blue)
   (faint blue-faint)
   (visited purple))
  (terminal
   (black bg-alt)
   (red red)
   (green green)
   (yellow yellow)
   (blue blue)
   (magenta magenta)
   (cyan cyan)
   (white fg-active)
   (bright-black border)
   (bright-red red-strong)
   (bright-green green-strong)
   (bright-yellow yellow-strong)
   (bright-blue blue-strong)
   (bright-magenta magenta-strong)
   (bright-cyan cyan-strong)
   (bright-white fg-active))
  (tokens
   (bg-dim (oklch 0.2478 0.0099 268.3))
   (bg-alt (oklch 0.3006 0.0116 264.4))
   (bg-alt-2 (oklch 0.3375 0.0163 270.9))
   (bg-active (oklch 0.3375 0.0163 270.9))
   (bg-hover bg-alt)
   (bg-hover-secondary bg-active)
   (bg-hl-line (oklch 0.2566 0.0116 270.9))
   (bg-selected bg-region)
   (bg-tab-bar bg-dim)
   (bg-tab-current bg-main)
   (bg-tab-other bg-alt)
   (bg-header bg-active)
   (bg-header-strong bg-active)
   (bg-tooltip bg-active)
   (bg-completion bg-alt)
   (bg-popup bg-alt)
   (bg-prose-block bg-alt)
   (bg-prose-block-contents bg-dim)
   (bg-markup-code bg-dim)
   (fg-muted (oklch 0.7093 0.0184 256.3))
   (fg-dim (oklch 0.6351 0.0165 260.7))
   (fg-faint (oklch 0.6351 0.0165 260.7))
   (fg-active (oklch 0.8744 0.0152 260.7))
   (fg-inverse bg-main)
   (fg-header-inverse bg-main)
   (border (oklch 0.3253 0.0148 269.2))
   (border-subtle bg-dim)
   (border-strong bg-active)
   (red-faint (oklch 0.6384 0.0949 14.1))
   (red-strong (oklch 0.6970 0.1943 19.4))
   (orange-faint (oklch 0.5137 0.0576 63.1))
   (orange-strong (oklch 0.6685 0.0844 64.9))
   (yellow-faint (oklch 0.6896 0.0500 88.3))
   (yellow-strong (oklch 0.7517 0.1164 84.2))
   (green-faint (oklch 0.5502 0.0654 132.5))
   (green-strong (oklch 0.7613 0.1068 132.1))
   (teal-faint (oklch 0.5733 0.0418 215.4))
   (teal-strong (oklch 0.7000 0.0889 207.7))
   (cyan-faint (oklch 0.5733 0.0418 215.4))
   (cyan-strong (oklch 0.7000 0.0889 207.7))
   (blue-faint (oklch 0.3912 0.0230 243.5))
   (blue-strong (oklch 0.6451 0.1013 244.3))
   (purple-faint (oklch 0.4707 0.0908 316.4))
   (purple-strong (oklch 0.6090 0.1170 318.1))
   (magenta-faint (oklch 0.5612 0.0466 347.2))
   (magenta-strong (oklch 0.6144 0.0997 347.1))
   (accent-0-subtle blue-subtle)
   (accent-1-subtle purple-subtle)
   (accent-2-subtle green-subtle)
   (accent-3-subtle orange-subtle)
   (accent-0-intense blue-strong)
   (accent-1-intense purple-strong)
   (accent-2-intense green-strong)
   (accent-3-intense orange-strong))
  (roles
   (variable-pitch-text :fg fg-main :bg bg-main
                        :family-var bv-themes-font-family-proportional
                        :height 1.0)
   (strong :fg fg-main :weight medium)
   (salient :fg fg-salient :weight medium)
   (special :fg fg-special :weight medium)
   (escape :fg syntax-escape :weight medium)
   (match :fg fg-main :bg bg-match :weight medium)
   (search :fg fg-search :bg bg-search :weight medium)
   (search-current :fg fg-search-current :bg bg-search-current
                   :weight medium)
   (paren :fg fg-paren :bg bg-paren :weight medium)
   (link :fg fg-link :underline nil)
   (link-visited :fg fg-link-visited :underline nil)
   (link-muted :fg fg-link-faint :underline nil)
   (prompt :fg prompt :weight medium)
   (keybind :fg keybind :weight medium)
   (success :fg success :weight medium)
   (warning :fg warning-strong :weight medium)
   (error :fg error-strong :weight medium)
   (info :fg info-strong :weight medium)
   (syntax-regexp :fg syntax-regexp :weight medium)
   (syntax-escape :fg syntax-escape :weight medium)
   (syntax-keyword :fg syntax-keyword :weight medium)
   (syntax-builtin :fg syntax-builtin)
   (syntax-function :fg syntax-function :weight medium)
   (syntax-constant :fg syntax-constant)
   (syntax-type :fg syntax-type)
   (syntax-preprocessor :fg syntax-preprocessor :weight medium)
   (line-number-current :fg fg-main :bg bg-hl-line)
   (header-default :fg fg-header :bg bg-header :extend t)
   (header-muted :fg fg-header-muted :bg bg-header :extend t)
   (header-strong :fg fg-header :bg bg-header :weight medium :extend t)
   (header-salient :fg fg-salient :bg bg-header
                   :weight medium :extend t)
   (header-popout :fg fg-header-inverse :bg modeline-bg-active
                  :weight medium :extend t)
   (mode-line-active :fg modeline-fg-active :bg modeline-bg-active)
   (mode-line-inactive :fg modeline-fg-inactive :bg modeline-bg-inactive)
   (mode-line-accent :fg modeline-fg-accent :bg modeline-bg-accent
                     :weight medium)
   (tab-current :fg fg-main :bg bg-tab-current :weight medium)
   (completion-current :fg fg-main :bg bg-completion-current
                       :weight medium :extend t)
   (completion-match :fg fg-salient :weight medium)
   (button :fg fg-link :bg bg-hover :underline nil :weight medium)
   (heading-1 :fg prose-heading-1 :weight medium :height 1.0)
   (heading-2 :fg prose-heading-2 :weight medium :height 1.0)
   (heading-3 :fg prose-heading-3 :weight medium :height 1.0)
   (heading-4 :fg prose-heading-4 :weight medium :height 1.0)
   (heading-5 :fg prose-heading-5 :height 1.0)
   (heading-6 :fg prose-heading-6 :height 1.0)
   (heading-7 :fg prose-heading-7 :height 1.0)
   (heading-8 :fg prose-heading-8 :height 1.0)
   (prose-title :fg blue-strong :weight bold :height 1.1
                :family-var bv-themes-font-family-proportional)
   (prose-subtitle :fg fg-muted :height 1.0
                   :family-var bv-themes-font-family-proportional)
   (prose-todo :fg prose-todo :weight medium)
   (prose-done :fg prose-done :weight medium)
   (diff-added-refine :fg fg-added :bg bg-added-refine :weight medium)
   (diff-removed-refine :fg fg-removed :bg bg-removed-refine
                        :weight medium)
   (diff-changed-refine :fg fg-changed :bg bg-changed-refine
                        :weight medium)
   (diff-header :fg fg-main :bg bg-alt :weight medium :extend t)
   (diff-file-header :fg fg-salient :bg bg-alt-2
                     :weight medium :extend t)
   (vc-added :fg fg-added :weight medium)
   (vc-removed :fg fg-removed :weight medium)
   (vc-changed :fg fg-changed :weight medium)
   (calendar-header :fg prose-heading-1 :weight medium)
   (calendar-today :fg blue-strong :weight medium)
   (calendar-current :fg fg-main :bg bg-region :weight medium)
   (bv-gallery-title :define t :fg prose-heading-1
                     :weight medium :height 1.0)
   (bv-gallery-summary :define t :fg fg-muted)
   (bv-gallery-swatch-label :define t :fg fg-dim)
   (bv-gallery-swatch-border :define t :fg border-subtle))
  (faces
   (bv-theme-gallery-title bv-gallery-title)
   (bv-theme-gallery-summary bv-gallery-summary)
   (bv-theme-gallery-swatch-label bv-gallery-swatch-label)
   (bv-theme-gallery-swatch-border bv-gallery-swatch-border))
  (gallery
   :swatches '(neutral state accent syntax prose terminal)
   :samples '(code diff org minibuffer modeline calendar feeds terminal)
   :background 'charcoal
   :density 'high)
  (policy
   :underlines nil
   :contrast-target 'aesthetic
   :terminal-colors 256
   :gamut 'srgb)
  (samples
   (code "async fn refresh_buffer")
   (prose "* Night reading queue")
   (diff "- stale adapter edge"))
  (notes
   "Dark restores the charcoal Ink and Frost look with softened surfaces, restrained accents, and flat document typography."))

;;; bv-dark-theme.el ends here
