;;; bv-light-theme.el --- BV light theme specification -*- lexical-binding: t -*-

;; Copyright (C) 2026 Ayan Das
;; Author: Ayan Das <bvits@riseup.net>

;;; Commentary:

;; Ink and Frost light profile authored with perceptual anchors and semantic
;; role overrides.

;;; Code:

(require 'bv-themes)

(bv-themes-define-theme bv-light
  (metadata
   :display-name "BV Light"
   :summary "Ink and Frost light profile with paper-white surfaces, cool ink accents, and quiet editing chrome."
   :tags '(light paper ink frost prose code terminal)
   :family 'ink-and-frost
   :version 2)
  (variant light
   :polarity 1
   :modes '(gui tty)
   :ambient 'day)
  (anchors
   (neutral
    (bg-main (oklch 0.9886 0.0026 286.4))
    (bg-dim (oklch 0.9670 0.0029 264.5))
    (fg-main (oklch 0.3496 0.0141 274.5)))
   (state
    (red (oklch 0.6391 0.1792 28.3))
    (orange (oklch 0.6952 0.1294 54.4))
    (yellow (oklch 0.6584 0.1380 76.2))
    (green (oklch 0.6381 0.1419 143.5)))
   (accent
    (teal (oklch 0.6652 0.1154 211.3))
    (cyan (oklch 0.5814 0.1271 237.2))
    (blue (oklch 0.6017 0.1930 263.2))
    (purple (oklch 0.5236 0.2110 328.8))
    (magenta (oklch 0.6012 0.1802 327.9))))
  (surfaces
   (bg-alt :amount 0.052 :intent quiet-layer)
   (bg-alt-2 :amount 0.082 :intent raised-layer)
   (bg-active :amount 0.118 :intent active-row)
   (bg-hover :amount 0.060 :intent pointer-target)
   (bg-hover-secondary :amount 0.064 :intent secondary-target)
   (bg-region :amount 0.220 :intent selection)
   (bg-region-subtle :amount 0.140 :intent secondary-selection)
   (bg-hl-line :amount 0.038 :intent reading-line)
   (bg-header :amount 0.000 :intent structural-band)
   (bg-header-strong :amount 0.052 :intent prominent-band)
   (bg-completion-current :amount 0.170 :intent completion-focus)
   (bg-prose-block-contents :amount 0.038 :intent prose-block)
   (bg-markup-code :amount 0.054 :intent inline-code)
   (fg-muted :amount 0.680 :intent secondary-text)
   (fg-dim :amount 0.560 :intent tertiary-text)
   (fg-faint :amount 0.450 :intent disabled-text)
   (border :amount 0.178 :intent visible-boundary)
   (border-subtle :amount 0.106 :intent quiet-boundary)
   (border-strong :amount 0.315 :intent emphasized-boundary))
  (tones
   (faint :amount 0.700)
   (subtle :amount 0.154)
   (subtle-2 :amount 0.232)
   (strong-chroma-scale :amount 1.060))
  (ui
   (salient blue)
   (special purple)
   (special-mild purple-faint)
   (header fg-active)
   (header-muted fg-muted)
   (cursor blue)
   (prompt orange-strong)
   (keybind blue)
   (accent-0 blue)
   (accent-1 purple)
   (accent-2 green)
   (accent-3 orange))
  (syntax
   (comment (oklch 0.6438 0.0138 271.2))
   (doc green-faint)
   (string green)
   (regexp purple)
   (escape (oklch 0.5460 0.2126 3.2))
   (keyword purple)
   (builtin cyan)
   (function blue)
   (variable red)
   (constant cyan)
   (number yellow)
   (type yellow)
   (operator fg-muted)
   (preprocessor orange)
   (property fg-main)
   (bracket fg-main)
   (delimiter fg-muted))
  (prose
   (heading-1 fg-main)
   (heading-2 yellow-strong)
   (heading-3 fg-active)
   (heading-4 blue-strong)
   (heading-5 green-strong)
   (heading-6 purple-strong)
   (heading-7 orange-strong)
   (heading-8 fg-muted)
   (link blue)
   (visited purple)
   (code (oklch 0.6012 0.1802 327.9))
   (verbatim teal)
   (metadata fg-muted)
   (metadata-value fg-active)
   (table fg-main)
   (todo red)
   (done green))
  (states
   (success green)
   (success-strong green-strong)
   (warning yellow)
   (warning-strong yellow-strong)
   (error red)
   (error-strong red-strong)
   (info cyan)
   (info-strong cyan-strong)
   (critical red)
   (critical-bg (tone red subtle))
   (critical-fg fg-main))
  (search
   (background (mix yellow bg-main 0.260))
   (foreground fg-main)
   (current-background (mix orange bg-main 0.280))
   (current-foreground fg-main)
   (lazy-background (mix cyan bg-main 0.180))
   (match-background (mix cyan bg-main 0.240))
   (paren-background (oklch 0.8929 0.0362 228.5))
   (paren-foreground fg-main))
  (diff
   (added-background (tone green subtle))
   (added-refine (tone green subtle-2))
   (added-foreground green-strong)
   (removed-background (tone red subtle))
   (removed-refine (tone red subtle-2))
   (removed-foreground red-strong)
   (changed-background (tone yellow subtle))
   (changed-refine (tone yellow subtle-2))
   (changed-foreground yellow-strong))
  (modeline
   (active-background (oklch 0.9233 0.0067 286.3))
   (active-foreground fg-active)
   (inactive-background (oklch 0.9560 0.0040 286.3))
   (inactive-foreground fg-dim)
   (active-border (oklch 0.8591 0.0068 286.3))
   (inactive-border (oklch 0.9081 0.0067 286.3))
   (accent-background blue)
   (accent-foreground bg-main)
   (critical-background red)
   (critical-foreground bg-main))
  (links
   (normal blue)
   (faint blue-faint)
   (visited purple))
  (terminal
   (black fg-active)
   (red red)
   (green green)
   (yellow yellow)
   (blue blue)
   (magenta magenta)
   (cyan cyan)
   (white modeline-bg-active)
   (bright-black fg-muted)
   (bright-red red-strong)
   (bright-green green-strong)
   (bright-yellow yellow-strong)
   (bright-blue blue-strong)
   (bright-magenta magenta-strong)
   (bright-cyan cyan-strong)
   (bright-white bg-main))
  (tokens
   (bg-dim (oklch 0.9670 0.0029 264.5))
   (bg-alt (oklch 0.9379 0.0040 286.3))
   (bg-alt-2 (oklch 0.9081 0.0067 286.3))
   (bg-active (oklch 0.9081 0.0067 286.3))
   (bg-hover (oklch 0.9560 0.0040 286.3))
   (bg-hover-secondary (oklch 0.9319 0.0040 286.3))
   (bg-hl-line bg-dim)
   (bg-selected bg-region)
   (bg-tab-bar bg-alt)
   (bg-tab-current bg-main)
   (bg-tab-other bg-dim)
   (bg-header bg-active)
   (bg-header-strong bg-active)
   (bg-tooltip bg-main)
   (bg-completion bg-alt)
   (bg-popup bg-dim)
   (bg-prose-block bg-alt)
   (bg-prose-block-contents bg-dim)
   (bg-markup-code bg-dim)
   (fg-muted (oklch 0.5418 0.0129 269.4))
   (fg-dim (oklch 0.6438 0.0138 271.2))
   (fg-faint (oklch 0.6438 0.0138 271.2))
   (fg-active (oklch 0.2925 0.0157 264.3))
   (fg-inverse bg-main)
   (fg-header-inverse bg-main)
   (border (oklch 0.8591 0.0068 286.3))
   (border-subtle (oklch 0.9081 0.0067 286.3))
   (border-strong (oklch 0.8591 0.0068 286.3))
   (red-faint (oklch 0.7245 0.0786 25.1))
   (red-strong (oklch 0.6279 0.2242 29.9))
   (orange-faint (oklch 0.7501 0.0602 57.3))
   (orange-strong (oklch 0.6862 0.1633 50.9))
   (yellow-faint (oklch 0.6962 0.1249 82.7))
   (yellow-strong (oklch 0.6084 0.1279 75.8))
   (green-faint (oklch 0.6875 0.0805 144.1))
   (green-strong (oklch 0.6146 0.1533 143.2))
   (teal-faint (oklch 0.6312 0.1093 230.4))
   (teal-strong (oklch 0.5365 0.1177 237.3))
   (cyan-faint (oklch 0.6312 0.1093 230.4))
   (cyan-strong (oklch 0.5365 0.1177 237.3))
   (blue-faint (oklch 0.7197 0.0858 264.8))
   (blue-strong (oklch 0.5654 0.2388 262.8))
   (purple-faint (oklch 0.5865 0.1705 328.3))
   (purple-strong (oklch 0.5038 0.2171 328.9))
   (magenta-faint (oklch 0.6804 0.0887 327.2))
   (magenta-strong (oklch 0.5767 0.2067 328.2))
   (accent-0-subtle blue-subtle)
   (accent-1-subtle purple-subtle)
   (accent-2-subtle green-subtle)
   (accent-3-subtle orange-subtle)
   (accent-0-intense blue-strong)
   (accent-1-intense purple-strong)
   (accent-2-intense green-strong)
   (accent-3-intense orange-strong))
  (roles
   (variable-pitch-text :fg fg-main :bg bg-main
                        :family-var bv-themes-font-family-proportional
                        :height 1.0)
   (strong :fg fg-main :weight medium)
   (salient :fg fg-salient :weight medium)
   (special :fg fg-special :weight medium)
   (escape :fg syntax-escape :weight medium)
   (match :fg fg-main :bg bg-match :weight medium)
   (search :fg fg-search :bg bg-search :weight medium)
   (search-current :fg fg-search-current :bg bg-search-current
                   :weight medium)
   (paren :fg fg-paren :bg bg-paren :weight medium)
   (link :fg fg-link :underline nil)
   (link-visited :fg fg-link-visited :underline nil)
   (link-muted :fg fg-link-faint :underline nil)
   (prompt :fg prompt :weight medium)
   (keybind :fg keybind :weight medium)
   (success :fg success :weight medium)
   (warning :fg warning-strong :weight medium)
   (error :fg error-strong :weight medium)
   (info :fg info-strong :weight medium)
   (syntax-regexp :fg syntax-regexp :weight medium)
   (syntax-escape :fg syntax-escape :weight medium)
   (syntax-keyword :fg syntax-keyword :weight medium)
   (syntax-builtin :fg syntax-builtin)
   (syntax-function :fg syntax-function :weight medium)
   (syntax-constant :fg syntax-constant)
   (syntax-type :fg syntax-type)
   (syntax-preprocessor :fg syntax-preprocessor :weight medium)
   (line-number-current :fg fg-main :bg bg-hl-line)
   (header-default :fg fg-header :bg bg-header :extend t)
   (header-muted :fg fg-header-muted :bg bg-header :extend t)
   (header-strong :fg fg-header :bg bg-header :weight medium :extend t)
   (header-salient :fg fg-salient :bg bg-header
                   :weight medium :extend t)
   (header-popout :fg fg-header-inverse :bg modeline-bg-active
                  :weight medium :extend t)
   (mode-line-active :fg modeline-fg-active :bg modeline-bg-active)
   (mode-line-inactive :fg modeline-fg-inactive :bg modeline-bg-inactive)
   (mode-line-accent :fg modeline-fg-accent :bg modeline-bg-accent
                     :weight medium)
   (tab-current :fg fg-main :bg bg-tab-current :weight medium)
   (completion-current :fg fg-main :bg bg-completion-current
                       :weight medium :extend t)
   (completion-match :fg fg-salient :weight medium)
   (button :fg fg-link :bg bg-hover :underline nil :weight medium)
   (heading-1 :fg prose-heading-1 :weight medium :height 1.0)
   (heading-2 :fg prose-heading-2 :weight medium :height 1.0)
   (heading-3 :fg prose-heading-3 :weight medium :height 1.0)
   (heading-4 :fg prose-heading-4 :weight medium :height 1.0)
   (heading-5 :fg prose-heading-5 :height 1.0)
   (heading-6 :fg prose-heading-6 :height 1.0)
   (heading-7 :fg prose-heading-7 :height 1.0)
   (heading-8 :fg prose-heading-8 :height 1.0)
   (prose-title :fg blue-strong :weight bold :height 1.1
                :family-var bv-themes-font-family-proportional)
   (prose-subtitle :fg fg-muted :height 1.0
                   :family-var bv-themes-font-family-proportional)
   (prose-todo :fg prose-todo :weight medium)
   (prose-done :fg prose-done :weight medium)
   (diff-added-refine :fg fg-added :bg bg-added-refine :weight medium)
   (diff-removed-refine :fg fg-removed :bg bg-removed-refine
                        :weight medium)
   (diff-changed-refine :fg fg-changed :bg bg-changed-refine
                        :weight medium)
   (diff-header :fg fg-main :bg bg-alt :weight medium :extend t)
   (diff-file-header :fg fg-salient :bg bg-alt-2
                     :weight medium :extend t)
   (vc-added :fg fg-added :weight medium)
   (vc-removed :fg fg-removed :weight medium)
   (vc-changed :fg fg-changed :weight medium)
   (calendar-header :fg prose-heading-1 :weight medium)
   (calendar-today :fg blue-strong :weight medium)
   (calendar-current :fg fg-main :bg bg-region :weight medium)
   (bv-gallery-title :define t :fg prose-heading-1
                     :weight medium :height 1.0)
   (bv-gallery-summary :define t :fg fg-muted)
   (bv-gallery-swatch-label :define t :fg fg-dim)
   (bv-gallery-swatch-border :define t :fg border-subtle))
  (faces
   (bv-theme-gallery-title bv-gallery-title)
   (bv-theme-gallery-summary bv-gallery-summary)
   (bv-theme-gallery-swatch-label bv-gallery-swatch-label)
   (bv-theme-gallery-swatch-border bv-gallery-swatch-border))
  (gallery
   :swatches '(neutral state accent syntax prose terminal)
   :samples '(code diff org minibuffer modeline calendar feeds terminal)
   :background 'paper
   :density 'high)
  (policy
   :underlines nil
   :contrast-target 'aesthetic
   :terminal-colors 256
   :gamut 'srgb)
  (samples
   (code "defun map-window-state")
   (prose "* Project notes")
   (diff "+ refined token role"))
  (notes
   "Light restores the paper-white Ink and Frost look with cool accents, restrained weights, and flat document typography."))

;;; bv-light-theme.el ends here
