;;; bv-light-theme.el --- BV light theme specification -*- lexical-binding: t -*-

;; Copyright (C) 2026 Ayan Das
;; Author: Ayan Das <bvits@riseup.net>

;;; Commentary:

;; Ink and Frost light profile authored with perceptual anchors and semantic
;; role overrides.

;;; Code:

(require 'bv-themes)

(bv-themes-define-theme bv-light
  (metadata
   :display-name "BV Light"
   :summary "Washi paper light profile with sumi ink, indigo-cobalt structure, and elemental pigment accents."
   :tags '(light washi paper sumi ink indigo pigment prose code terminal)
   :family 'ink-and-frost
   :version 3)
  (variant light
   :polarity 1
   :modes '(gui tty)
   :ambient 'day)
  (anchors
   (neutral
    (bg-main (oklch 0.9810 0.0105 92.0))
    (bg-dim (oklch 0.9490 0.0100 96.0))
    (fg-main (oklch 0.2300 0.0180 260.0)))
   (state
    (red (oklch 0.5600 0.1450 30.0))
    (orange (oklch 0.6300 0.1050 58.0))
    (yellow (oklch 0.6900 0.1050 100.0))
    (green (oklch 0.5500 0.0850 136.0)))
   (accent
    (teal (oklch 0.5480 0.0750 188.0))
    (cyan (oklch 0.5100 0.0850 222.0))
    (blue (oklch 0.4560 0.1450 263.0))
    (purple (oklch 0.4700 0.1150 306.0))
    (magenta (oklch 0.4920 0.1050 336.0))))
  (surfaces
   (bg-alt :amount 0.052 :intent quiet-layer)
   (bg-alt-2 :amount 0.082 :intent raised-layer)
   (bg-active :amount 0.118 :intent active-row)
   (bg-hover :amount 0.070 :intent pointer-target)
   (bg-hover-secondary :amount 0.064 :intent secondary-target)
   (bg-region :amount 0.235 :intent selection)
   (bg-region-subtle :amount 0.140 :intent secondary-selection)
   (bg-hl-line :amount 0.050 :intent reading-line)
   (bg-header :amount 0.000 :intent structural-band)
   (bg-header-strong :amount 0.052 :intent prominent-band)
   (bg-completion-current :amount 0.200 :intent completion-focus)
   (bg-prose-block-contents :amount 0.038 :intent prose-block)
   (bg-markup-code :amount 0.054 :intent inline-code)
   (fg-muted :amount 0.680 :intent secondary-text)
   (fg-dim :amount 0.560 :intent tertiary-text)
   (fg-faint :amount 0.450 :intent disabled-text)
   (border :amount 0.178 :intent visible-boundary)
   (border-subtle :amount 0.106 :intent quiet-boundary)
   (border-strong :amount 0.315 :intent emphasized-boundary))
  (tones
   (faint :amount 0.700)
   (subtle :amount 0.154)
   (subtle-2 :amount 0.232)
   (strong-chroma-scale :amount 1.045))
  (ui
   (salient blue-strong)
   (special purple-strong)
   (special-mild purple-faint)
   (header fg-active)
   (header-muted fg-muted)
   (cursor blue-strong)
   (prompt orange-strong)
   (keybind blue-strong)
   (accent-0 blue)
   (accent-1 purple)
   (accent-2 green)
   (accent-3 orange))
  (syntax
   (comment (oklch 0.5660 0.0180 265.0))
   (doc teal-faint)
   (string green-strong)
   (regexp magenta-strong)
   (escape red-strong)
   (keyword purple)
   (builtin cyan)
   (function blue)
   (variable fg-main)
   (constant magenta)
   (number orange)
   (type teal)
   (operator fg-muted)
   (preprocessor orange)
   (property fg-main)
   (bracket fg-main)
   (delimiter fg-muted))
  (prose
   (heading-1 blue-strong)
   (heading-2 fg-main)
   (heading-3 teal-strong)
   (heading-4 purple-strong)
   (heading-5 orange-strong)
   (heading-6 green-strong)
   (heading-7 yellow-strong)
   (heading-8 fg-muted)
   (link blue)
   (visited purple)
   (code magenta-strong)
   (verbatim cyan-strong)
   (metadata fg-muted)
   (metadata-value fg-active)
   (table fg-main)
   (todo red)
   (done green))
  (states
   (success green)
   (success-strong green-strong)
   (warning yellow)
   (warning-strong yellow-strong)
   (error red)
   (error-strong red-strong)
   (info cyan)
   (info-strong cyan-strong)
   (critical red)
   (critical-bg (tone red subtle))
   (critical-fg fg-main))
  (search
   (background (mix yellow bg-main 0.260))
   (foreground fg-main)
   (current-background (mix orange bg-main 0.290))
   (current-foreground fg-main)
   (lazy-background (mix cyan bg-main 0.180))
   (match-background (mix green bg-main 0.220))
   (paren-background (mix blue bg-main 0.210))
   (paren-foreground fg-main))
  (diff
   (added-background (tone green subtle))
   (added-refine (tone green subtle-2))
   (added-foreground green-strong)
   (removed-background (tone red subtle))
   (removed-refine (tone red subtle-2))
   (removed-foreground red-strong)
   (changed-background (tone yellow subtle))
   (changed-refine (tone yellow subtle-2))
   (changed-foreground yellow-strong))
  (modeline
   (active-background (oklch 0.2360 0.0270 260.0))
   (active-foreground bg-main)
   (inactive-background (oklch 0.9400 0.0105 96.0))
   (inactive-foreground fg-dim)
   (active-border (oklch 0.2360 0.0270 260.0))
   (inactive-border (oklch 0.8720 0.0130 96.0))
   (accent-background blue)
   (accent-foreground bg-main)
   (critical-background red)
   (critical-foreground bg-main))
  (links
   (normal blue)
   (faint blue-faint)
   (visited purple))
  (terminal
   (black fg-active)
   (red red)
   (green green)
   (yellow yellow)
   (blue blue)
   (magenta magenta)
   (cyan cyan)
   (white modeline-bg-active)
   (bright-black fg-muted)
   (bright-red red-strong)
   (bright-green green-strong)
   (bright-yellow yellow-strong)
   (bright-blue blue-strong)
   (bright-magenta magenta-strong)
   (bright-cyan cyan-strong)
   (bright-white bg-main))
  (tokens
   (bg-dim (oklch 0.9490 0.0100 96.0))
   (bg-alt (oklch 0.9530 0.0115 94.0))
   (bg-alt-2 (oklch 0.9190 0.0140 94.0))
   (bg-active (oklch 0.9040 0.0160 94.0))
   (bg-hover (oklch 0.9430 0.0140 96.0))
   (bg-hover-secondary (oklch 0.9250 0.0140 96.0))
   (bg-hl-line (oklch 0.9550 0.0120 94.0))
   (bg-region (mix blue bg-main 0.240))
   (bg-region-subtle (mix blue bg-main 0.155))
   (bg-selected bg-region)
   (bg-tab-bar bg-alt)
   (bg-tab-current bg-main)
   (bg-tab-other bg-dim)
   (bg-header bg-active)
   (bg-header-strong bg-active)
   (bg-tooltip bg-main)
   (bg-completion (oklch 0.9460 0.0115 94.0))
   (bg-completion-current (mix cyan bg-main 0.255))
   (bg-popup bg-dim)
   (bg-prose-block bg-alt)
   (bg-prose-block-contents bg-dim)
   (bg-markup-code bg-dim)
   (fg-muted (oklch 0.4380 0.0180 258.0))
   (fg-dim (oklch 0.5600 0.0140 258.0))
   (fg-faint (oklch 0.6880 0.0120 258.0))
   (fg-active (oklch 0.1920 0.0210 258.0))
   (fg-inverse bg-main)
   (fg-header-inverse bg-main)
   (border (oklch 0.8400 0.0140 94.0))
   (border-subtle (oklch 0.8900 0.0105 94.0))
   (border-strong (oklch 0.7600 0.0180 94.0))
   (red-faint (oklch 0.6800 0.0600 30.0))
   (red-strong (oklch 0.5020 0.1680 30.0))
   (orange-faint (oklch 0.7150 0.0520 58.0))
   (orange-strong (oklch 0.5650 0.1250 58.0))
   (yellow-faint (oklch 0.7480 0.0600 100.0))
   (yellow-strong (oklch 0.5600 0.1120 100.0))
   (green-faint (oklch 0.6400 0.0500 136.0))
   (green-strong (oklch 0.4900 0.1080 136.0))
   (teal-faint (oklch 0.6400 0.0420 188.0))
   (teal-strong (oklch 0.4750 0.0920 188.0))
   (cyan-faint (oklch 0.6300 0.0460 222.0))
   (cyan-strong (oklch 0.4580 0.1050 222.0))
   (blue-faint (oklch 0.6400 0.0700 263.0))
   (blue-strong (oklch 0.4200 0.1650 263.0))
   (purple-faint (oklch 0.6150 0.0650 306.0))
   (purple-strong (oklch 0.4250 0.1320 306.0))
   (magenta-faint (oklch 0.6350 0.0600 336.0))
   (magenta-strong (oklch 0.4450 0.1240 336.0))
   (accent-0-subtle blue-subtle)
   (accent-1-subtle purple-subtle)
   (accent-2-subtle green-subtle)
   (accent-3-subtle orange-subtle)
   (accent-0-intense blue-strong)
   (accent-1-intense purple-strong)
   (accent-2-intense green-strong)
   (accent-3-intense orange-strong))
  (roles
   (variable-pitch-text :fg fg-main :bg bg-main
                        :family-var bv-themes-font-family-proportional
                        :height 1.0)
   (strong :fg fg-main :weight medium)
   (salient :fg fg-salient :weight medium)
   (special :fg fg-special :weight medium)
   (escape :fg syntax-escape :weight medium)
   (match :fg fg-main :bg bg-match :weight medium)
   (search :fg fg-search :bg bg-search :weight medium)
   (search-current :fg fg-search-current :bg bg-search-current
                   :weight medium)
   (paren :fg fg-paren :bg bg-paren :weight medium)
   (link :fg fg-link :underline nil)
   (link-visited :fg fg-link-visited :underline nil)
   (link-muted :fg fg-link-faint :underline nil)
   (prompt :fg prompt :weight medium)
   (keybind :fg keybind :weight medium)
   (success :fg success :weight medium)
   (warning :fg warning-strong :weight medium)
   (error :fg error-strong :weight medium)
   (info :fg info-strong :weight medium)
   (syntax-regexp :fg syntax-regexp :weight medium)
   (syntax-escape :fg syntax-escape :weight medium)
   (syntax-keyword :fg syntax-keyword :weight medium)
   (syntax-builtin :fg syntax-builtin)
   (syntax-function :fg syntax-function :weight medium)
   (syntax-constant :fg syntax-constant)
   (syntax-type :fg syntax-type)
   (syntax-preprocessor :fg syntax-preprocessor :weight medium)
   (line-number-current :fg fg-main :bg bg-hl-line)
   (header-default :fg fg-header :bg bg-header :extend t)
   (header-muted :fg fg-header-muted :bg bg-header :extend t)
   (header-strong :fg fg-header :bg bg-header :weight medium :extend t)
   (header-salient :fg fg-salient :bg bg-header
                   :weight medium :extend t)
   (header-popout :fg fg-header-inverse :bg modeline-bg-active
                  :weight medium :extend t)
   (header-critical :fg modeline-fg-critical :bg modeline-bg-critical
                    :weight medium :extend t)
   (mode-line-active :fg modeline-fg-active :bg modeline-bg-active)
   (mode-line-inactive :fg modeline-fg-inactive :bg modeline-bg-inactive)
   (mode-line-accent :fg modeline-fg-accent :bg modeline-bg-accent
                     :weight medium)
   (tab-current :fg fg-main :bg bg-tab-current :weight medium)
   (completion-current :fg fg-main :bg bg-completion-current
                       :weight medium :extend t)
   (completion-match :fg fg-salient :weight medium)
   (button :fg fg-link :bg bg-hover :underline nil :weight medium)
   (heading-1 :fg prose-heading-1 :weight medium :height 1.0)
   (heading-2 :fg prose-heading-2 :weight medium :height 1.0)
   (heading-3 :fg prose-heading-3 :weight medium :height 1.0)
   (heading-4 :fg prose-heading-4 :weight medium :height 1.0)
   (heading-5 :fg prose-heading-5 :height 1.0)
   (heading-6 :fg prose-heading-6 :height 1.0)
   (heading-7 :fg prose-heading-7 :height 1.0)
   (heading-8 :fg prose-heading-8 :height 1.0)
   (prose-title :fg blue-strong :weight bold :height 1.1
                :family-var bv-themes-font-family-proportional)
   (prose-subtitle :fg fg-muted :height 1.0
                   :family-var bv-themes-font-family-proportional)
   (prose-todo :fg prose-todo :weight medium)
   (prose-done :fg prose-done :weight medium)
   (diff-added-refine :fg fg-added :bg bg-added-refine :weight medium)
   (diff-removed-refine :fg fg-removed :bg bg-removed-refine
                        :weight medium)
   (diff-changed-refine :fg fg-changed :bg bg-changed-refine
                        :weight medium)
   (diff-header :fg fg-main :bg bg-alt :weight medium :extend t)
   (diff-file-header :fg fg-salient :bg bg-alt-2
                     :weight medium :extend t)
   (vc-added :fg fg-added :weight medium)
   (vc-removed :fg fg-removed :weight medium)
   (vc-changed :fg fg-changed :weight medium)
   (calendar-header :fg prose-heading-1 :weight medium)
   (calendar-today :fg blue-strong :weight medium)
   (calendar-current :fg fg-main :bg bg-region :weight medium)
   (bv-gallery-title :define t :fg prose-heading-1
                     :weight medium :height 1.0)
   (bv-gallery-summary :define t :fg fg-muted)
   (bv-gallery-swatch-label :define t :fg fg-dim)
   (bv-gallery-swatch-border :define t :fg border-subtle))
  (faces
   (bv-theme-gallery-title bv-gallery-title)
   (bv-theme-gallery-summary bv-gallery-summary)
   (bv-theme-gallery-swatch-label bv-gallery-swatch-label)
   (bv-theme-gallery-swatch-border bv-gallery-swatch-border))
  (gallery
   :swatches '(neutral state accent syntax prose terminal)
   :samples '(code diff org minibuffer modeline calendar feeds terminal)
   :background 'paper
   :density 'high)
  (policy
   :underlines nil
   :contrast-target 'aesthetic
   :terminal-colors 256
   :gamut 'srgb)
  (samples
   (code "defun map-window-state")
   (prose "* Project notes")
   (diff "+ refined token role"))
  (notes
   "Light now reads as material pigment on washi: sumi text, indigo-cobalt structure, bengara and moss accents, oxidized copper blues, and yuzu used as a narrow highlight."))

;;; bv-light-theme.el ends here
